### ISSUE TITLE
Données de la table renseign_urb

### ISSUE THREAD

**Issue by jdenisgiguere** [sigrennesmetropole/addon_urbanisme#1]
Bonjour!

Est-ce possible d'avoir accès à un dump de données de la table renseign_urb?

@fvanderbiest  a déjà produit un modèle de données :  https://gist.github.com/fvanderbiest/f7cabbbd96b57d4b0dab . Les données permettraient d'effectuer les tests requis pour le développement.

Merci!

**Comment by catmorales** [comment]
Je vais vous en renvoyer un plus récent.


De : Jean-Denis Giguère [mailto:notifications@github.com]
Envoyé : mardi 3 mai 2016 11:39
À : sigrennesmetropole/addon_urbanisme
Objet : [sigrennesmetropole/addon_urbanisme] Données de la table renseign_urb (#1)


Bonjour!

Est-ce possible d'avoir accès à un dump de données de la table renseign_urb?

@fvanderbiest<https://github.com/fvanderbiest> a déjà produit un modèle de données : https://gist.github.com/fvanderbiest/f7cabbbd96b57d4b0dab . Les données permettraient d'effectuer les tests requis pour le développement.

Merci!

**Comment by jdenisgiguere** [comment]
:+1: 

Merci @catmorales,

**Comment by catmorales** [comment]
Je vous ai mis les dumps des 2 tables rensign_urba (schéma app_plu) et plu_zone_urba (schema urba_foncier) sur le site ftp de la ville de Rennes  dans un répertoire Camp2camp/dump
@fvanderbiest a les paramètres de connexion.
 Dites moi si vous préférez que je les mette ailleurs.

**Comment by fvanderbiest** [comment]
> Les données permettraient d'effectuer les tests requis pour le développement.

ftp://sig_ed:cub12%3fg@ftp.ville-rennes.fr/Camp2camp/data/

**Comment by jdenisgiguere** [comment]
Log filezilla
---------------

Statut :	Résolution de l'adresse de ftp.ville-rennes.fr
Statut :	Connexion à 194.206.58.70:21...
Erreur :	Connection interrompue après 20 secondes d'inactivité
Erreur :	Impossible d'établir une connexion au serveur

**Comment by jdenisgiguere** [comment]
La connexion ne semble pas fonctionner  ici. Est-ce qu'il y a des paramètres de connexion particuliers à connaitre?

**Comment by catmorales** [comment]
J'étais en réunion...
Merci de ne pas mettre les paramètres de connexion sur ce site qui est public.
Je vous envoie les dumps par mail

**Comment by catmorales** [comment]
* 6 MO pour renseign_urba en compressé , je viens de vous l'envoyer sur votre boîte gmail
* 3 Mo pour zonage plu, idem

**Comment by fvanderbiest** [comment]
> Merci de ne pas mettre les paramètres de connexion sur ce site qui est public.

oops ! 
sorry, j'avais oublié :-(

**Comment by jdenisgiguere** [comment]
Les dumps sont chargés localement.
Il faut d'abord créer manuellement les schémas.

Merci @catmorales!
