### ISSUE TITLE
[RU] Aucune infos venant de la table renseign_urba

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#10]
**Description du test:** 
Je souhaite interroger la parcelle "3500010000A0264" pour en avoir le  renseignement d'urbanisme .

J'ai vérifié préalablement dans la base que cette parcelle a bien de l'information disponible dans la table renseign_urba:
![image](https://cloud.githubusercontent.com/assets/4659829/17052704/e853b4d8-4ffe-11e6-8325-bd9c9bc354d7.png)
J'ai préchargées les 2 couches nécessaires à l'addon et activé les deux addons "cadastrapp" et "urbanisme" (noter au passage que la plupart des utilisateurs auront les 2 modules activés en permanence) .

1 - je me positionne sur cette parcelle grâce au module cadastre ,
![image](https://cloud.githubusercontent.com/assets/4659829/17053106/b7763e10-5000-11e6-88bb-8ddf6901a17c.png)

2- j'active le bouton "i orange" de la couche parcelle  pour avoir le renseignement d'urbanisme de cette parcelle et je clique sur la carte:
La fiche d'information qui s'ouvre ne contient pas la partie liée au règlement du PLU issue de la table renseign_urba:
![image](https://cloud.githubusercontent.com/assets/4659829/17053187/202eba04-5001-11e6-958f-d13890b46d51.png)
et un message d'erreur apparait au bout de quelques minutes:
![image](https://cloud.githubusercontent.com/assets/4659829/17053424/30a0f8f6-5002-11e6-83e5-0ae6e2c8b31e.png)

**Comment by catmorales** [comment]
Je rajoute que j'ai également fait le test en désactivant le module cadastre et en rechargeant mapfishapp et il se passe la même chose.

**Comment by catmorales** [comment]
Pour compléter j'ai vérifié également que la table app_plu.renseign_urba a bien les droits pour l'utilisateur intranet qui est paramétré dans la connexion de urbanisme.properties:
`ALTER TABLE app_plu.renseign_urba
  OWNER TO app_plu;
GRANT ALL ON TABLE app_plu.renseign_urba TO app_plu;
GRANT SELECT ON TABLE app_plu.renseign_urba TO intranet;`

**Comment by catmorales** [comment]
j'ai refait le même test aujourd'hui , le traitement pose problème si la couche parcelle est chargée deux fois (cas si le module cadastre est activé après avoir chargée cette couche) cf #7 sinon 
ça fonctionne :), car j'obtiens bien:
![image](https://cloud.githubusercontent.com/assets/4659829/17174604/015dc7ae-5403-11e6-9593-2af4a817918e.png)

:

**Comment by catmorales** [comment]
par contre dans l'impression j'ai toujours une carte "rose" cf #11

**Comment by catmorales** [comment]
le contenu du renseignement d'urbanisme ne semble pas correct , j'ouvre un autre ticket

**Comment by catmorales** [comment]
Je ne comprends  plus, je viens de réessayer et ça ne marche plus, je n'ai plus le renseignement d'urbanisme

**Comment by catmorales** [comment]
et longtemps après j'ai à nouveau un message d'erreur (HTTP 503)

**Comment by catmorales** [comment]
Je confirme.
J'ai ré-essayé ce jour et je n'arrive plus à avoir le renseignement d'urbanisme sous le tableau avec toujours le même message d'erreur http 503 qui arrrive longtemps après et dans les logs:
```
2016-08-01 14:35:14,861 [http-8480-32] DEBUG / - nouser - norole -o.s.web.servlet.DispatcherServlet - Last-Modified value for [/urbanisme/renseignUrba] is: -1
2016-08-01 14:35:14,861 [http-8480-32] DEBUG / - nouser - norole -o.s.w.b.a.s.HandlerMethodInvoker - Invoking request handler method: public void org.georchestra.urbanisme.RenseignUrbaController.getRenseignUrba(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse) throws java.lang.Exception
2016-08-01 14:41:37,254 [http-8480-29] DEBUG / - nouser - norole -o.s.web.servlet.DispatcherServlet - DispatcherServlet with name 'urbanisme' processing GET request for [/urbanisme/renseignUrba]
2016-08-01 14:41:37,254 [http-8480-29] DEBUG / - nouser - norole -o.s.w.s.m.a.DefaultAnnotationHandlerMapping - Mapping [/renseignUrba] to HandlerExecutionChain with handler [org.georchestra.urbanisme.RenseignUrbaController@1c66a766] and 1 interceptor
```

**Comment by catmorales** [comment]
re-testé ce jour et c'est opérationnel

**Comment by catmorales** [comment]
Je rouvre ce ticket car le problème est à nouveay présent suite à la démo faite ce matin . cette fonctionnalité ne marche plus . @pmauduit Paramétrage lors du passage en master ?
Problème à résoudre avant la livraison finale de VSR

**Comment by MaelREBOUX** [comment]
c'est ok sur intra test ce jour
