### ISSUE TITLE
[RU] PDF -Impossible d'imprimer le fond de plan WMS-C dans le renseignement d'urbanisme

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#11]
![image](https://cloud.githubusercontent.com/assets/4659829/17054013/2d9a0c12-5005-11e6-8442-8622864d2373.png)
 contexte:
![image](https://cloud.githubusercontent.com/assets/4659829/17054050/603e20fe-5005-11e6-8011-71a7fabdf4f1.png)

**Comment by catmorales** [comment]
@pmauduit N'y a t-il pas quelque chose à faire par rapport à ce message du urbanisme.properties ?
```
# if datadir mode, the following property should be set to file:///path/to/georchestra/datadir/urbanisme/templates
mapfishPrintDir=classpath:///templates
```

**Comment by pmauduit** [comment]
> Comme tu l'avais suggéré il faut peut être changer d'emplacement le répertoire des templates

Ce n'est pas obligatoire, si on laisse tel quel c'est celui dans la webapp qui sera utilisé ; après on va sans doute avoir besoin de les personnalier, donc on peut envisager de les sortir dans le datadir d'ores et déjà.

**Comment by pmauduit** [comment]
Pour la carte rose, je pense que c'est du à la fermeture de la plateforme, j'avais configuré directement dans la webapp les identifiants du geoserver_privileged_user mais cela a du sauter suite à un redéploiement.

**Comment by catmorales** [comment]
>mais cela a du sauter suite à un redéploiement.

Justement , je dois redéployer l'add-on cadastre sur la plateforme de test mais je suppose que je ne peux pas le faire par Jenkins car cela risque d'écraser l'addon atlas et l'addon urbanisme. @pmauduit tu confirmes ?

**Comment by catmorales** [comment]
Puisque tu ebn parles, l'addon cadastrapp a aussi eu des changements bizarres qui ont sauté dans les fichiers de configuration (différents de  ce qui est sur Github)

**Comment by pmauduit** [comment]
> l'addon cadastrapp a aussi eu des changements bizarres qui ont sauté dans les fichiers de configuration (différents de ce qui est sur Github)

Vous regardez bien dans `/srv/tomcat/cadastre/work/cadastrapp` pour les fichiers de conf ?

J'ai finalement sorti le template mfpv3 pour l'urbanisme (mais pas encore changé les droits sur les fichiers).

**Comment by catmorales** [comment]
> Vous regardez bien dans /srv/tomcat/cadastre/work/cadastrapp pour les fichiers de conf ?

 oui pour la webapp c'est bon  mais ce sont les fichiers de conf de l'addon qui ont sautés donc dans /srv/tomcat/georchestra/webapps/mapfishapp/app/addons/cadastrapp

**Comment by pmauduit** [comment]
Concernant cadastrapp et jenkins, on n'a jamais configuré de job, non ?

**Comment by catmorales** [comment]
non pas à ma connaissance

**Comment by catmorales** [comment]
> il me reste un paramétrage dans le manifest.json 
 c'est fait .
Il s'agit d'une erreur dans ` cadastrapp.infobulle.prefix**e**" : "Prefixe",` le e est à retirer . 

Ces 2 paramétrages  ont été corrigées sur https://github.com/camptocamp/georchestra-rennes-configuration/tree/15.12/mapfishapp/app/addons/cadastrapp en juin dernier mais si quelqu'un a redéployé les addons sans passer par github ça peut expliquer cela.

**Comment by pmauduit** [comment]
Pour la carte rose, c'est clairement dû à l'absence de basic-auth d'après les logs. Je demande à mon collègue spécialiste du mfpv3 en début de semaine prochaine comment configurer au niveau du yaml parce que mon essai n'est pas concluant.

**Comment by catmorales** [comment]
>c'est clairement dû à l'absence de basic-auth d'après les loGS;
je me demande si je n'ai pas le même problème avec la loupe et avec la vue de situation mais cela fait l'objet d'autres tickets sur le github camptocamp...

**Comment by pmauduit** [comment]
C'était bien un problème de basic-auth, mais il faut pouvoir déclencher un 401 pour que le mapfish-printv3 veuille bien utiliser les identifiants, j'ai donc configuré un user-agent compatible avec la configuration du security-proxy tel que déployé sur intra-test.

Au passage, il y a un soucis avec cadastrapp en version master, en effet il est nécessaire d'utiliser mapfishapp en version master pour pouvoir bénéficier du JS minifié, ce qui n'est pas le cas chez vous, j'ai donc modifié la configuration de l'addon cadastrapp pour remettre quelquechose qui soit compatible avec la plateforme (ou alors il faut fournir le fichier js/build/cadastrapp.js), cf le manifest.json de cadastrapp

**Comment by catmorales** [comment]
>Au passage, il y a un soucis avec cadastrapp en version master

Merci Pierre :) 
C'est pour cela que suite à la mise à jour d'hier sur le PF de test (mise à jour de l'addon qui était indispensable ), le module cadastrapp ne fonctionnait plus. 
A noter que je n'ai pas modifié l'addon sur github, car jene peux pas redéployer mapfishapp avec jenkins (risque d'écraser les autres addons )
Par contre que me conseilles tu de faire pour les prochaines mises à jour ?

**Comment by pmauduit** [comment]
> A noter que je n'ai pas modifié l'addon sur github, car jene peux pas redéployer mapfishapp avec jenkins (risque d'écraser les autres addons )

Qu'est ce qui poserait problème si les addons sont dans votre profil de configuration au moment du build de mapfishapp ?

**Comment by catmorales** [comment]
Qu'est ce qui poserait problème si les addons sont dans votre profil de configuration au moment du build de mapfishapp ?

Tant qu'ils ne sont pas validés et débuggués , si les nouveaux adddons ne fonctionnent pas, je ne pourrai pas déployer mapfishapp en prod intra et extra sinon les utilisateurs auront accès à des fonctionnalités non opérationnelles... à moins de les rendre non visibles par défaut ?

**Comment by pmauduit** [comment]
Ok, donc je ne voies pas de meilleure solution en attendant que de travailler sur test directement, valider le fonctionnement puis de créer les entrées dans le profil de conf une fois validé et qu'on est sur que ca fonctionne

**Comment by catmorales** [comment]
Oui c'est aussi ce que j'en avais conclu mais il faut que je puisse mettre à jor le module cadastre régulièrement quand même.

>j'ai donc modifié la configuration de l'addon cadastrapp pour remettre quelquechose qui soit compatible avec la plateforme 

* Puis je récupérer l'addon cadastrapp modifié par tes soins sur la PF de test pour le mettre sur github dans notre profil de configuration afin de mettre à jour également les PF de prod ?
* Faut-il demander à ce qu'il y ait une branche 15.12 sur https://github.com/georchestra/cadastrapp pour éviter ce problème lié à la minification ?

**Comment by catmorales** [comment]
ou faut-il faire ce que suggère Julien dans https://github.com/georchestra/cadastrapp/issues/240#issuecomment-235533299

**Comment by catmorales** [comment]
> cf le manifest.json de cadastrapp

ok vu.
Il suffit d'enlever ces deux premières lignes ?
dans ce cas, c'est simple,je peux faire une mise à jour sur github de l'addon cadastrapp pour la propager sur les PF...

@pmauduit tu valides ?

**Comment by pmauduit** [comment]
> Il suffit d'enlever ces deux premières lignes ?

oui: cf le commit qui a introduit l'utilisation des versions minifiées:

https://github.com/georchestra/cadastrapp/commit/ff1220fec52ccabc6b38e63bdeef8c3bf8eb4207#diff-2761bbf822ab6e59dfc8aaca15b28c49L2

ces js / debugjs ne sont pas pris en compte dans la version 15.12, il ne faut garder que le tableau "js"

**Comment by pmauduit** [comment]
> ou faut-il faire ce que suggère Julien dans georchestra/cadastrapp#240 (comment)

Je dois travailler cette semaine pour le déployer chez cigalsace, c'est certes du docker, mais j'aimerais faire en sorte que le processus de build de cadastrapp puisse à la fois fournir la webapp et un zip de l'addon pret à être déployé dans un mapfishapp (comme ce que j'ai fait précédemment sur le module urbanisme). Comme tout est branché sur des CI (jenkins) afin de rendre la chose le plus automatisable possible, je pense que cela sera intéressant pour vous aussi.

**Comment by catmorales** [comment]
En ce qui concerne la carte (objet de ce ticket),le renseignemenr d'urbanisme est maintenant bon cf #10  mais il y a toujours une carte "rose" cf le fichier joint
[mapfish-print-report (7).pdf](https://github.com/sigrennesmetropole/addon_urbanisme/files/385970/mapfish-print-report.7.pdf)

**Comment by pmauduit** [comment]
Bizarre, je viens de retester, et j'obtiens bien une carte:

![urba](https://cloud.githubusercontent.com/assets/594335/17174912/0b071cb8-5405-11e6-8e5c-01671df13576.png)

**Comment by catmorales** [comment]
as tu mis un contexte dessous ? le contexte cadastre notamment ...

**Comment by catmorales** [comment]
en effet sans le contexte ça marche ... embêtant ça

**Comment by pmauduit** [comment]
Quelles couches je dois avoir exactement pour pouvoir tester ? peut etre que l'utilisateur geoservr_privileged_user n'a pas les droits d'accès sur la couche cadastre ?

**Comment by catmorales** [comment]
charger une carte / choisir cadastre ou default

**Comment by catmorales** [comment]
> l'utilisateur geoservr_privileged_user n'a pas les droits d'accès sur la couche cadastre 

ce serait bizarre car il est déclaré dans geowebcache.xml

**Comment by fvanderbiest** [comment]
> pour l'impression il faudra peut être prendre la même carte en WMS servie par geoserver et non pas par geowebcache

Oui, il faudra mettre en place la même chose que https://github.com/georchestra/georchestra/commit/e07e89a6e2ed55499deb809bbcd5ed8aab08db95 pour l'Atlas

**Comment by catmorales** [comment]
@fjacon-  Relance , ce point bloquant devait être corrigé pour la fin de semaine dernière ou début de cette semaine, C'est ce que nous avions décidé  par rapport à  la  validation de la VA (cf mail du 04/10). C'est bien planifié dans vos agendas pour quand ?

**Comment by fvanderbiest** [comment]
J'y travaille ce jour.

Le 11 oct. 2016 09:47, "Catherine MORALES" <notifications@github.com> a
écrit :

**Comment by fvanderbiest** [comment]
A priori traité avec 34ed0c4, à tester sur la plateforme dédiée.
Je m'en charge.

**Comment by fvanderbiest** [comment]
It works !

**Comment by catmorales** [comment]
Super , je testerai demain !!!

**Comment by catmorales** [comment]
Ok c'est bon pour le fond :) mais je n'ai pas les autres couches:
![image](https://cloud.githubusercontent.com/assets/4659829/19390860/55dc17bc-922a-11e6-8c91-72b6e48d2c41.png)

https://portail-test.sig.rennesmetropole.fr/mapfishapp/map/56f08c17de5a573792fa16a04b721fb4

**Comment by catmorales** [comment]
Je ferme ce ticket et j'en ouvre un autre
