### ISSUE TITLE
[Général] Personnalisation paramétrable ?

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#12]
- Les polices de caractères utilisées dans les fiches d'informations sont elles paramétrables et où ? css de l'addon ?
- le bouton "i" orange:
  - est-il générique à l'ensemble des couches utilisées par l'addon ou peut-il être différent pour chacune des couches  ?
  -  est-il paramétrable  et  où ?

**Comment by jdenisgiguere** [comment]
Ce n'est pas implémenté pour le moment. Je reviens avec une proposition cette semaine.

**Comment by fvanderbiest** [comment]
> Les polices de caractères utilisées dans les fiches d'informations sont elles paramétrables et où ? css de l'addon ?

Oui

> est-il générique à l'ensemble des couches utilisées par l'addon 

Oui

> ou peut-il être différent pour chacune des couches ?

Non, pas en l'état actuel

> est-il paramétrable et où ?

Pas vraiment paramétrable, mais le code peut être modifié que ce soit dans votre datadir ou sur ce dépôt.

**Comment by catmorales** [comment]
Ca devrait aller pour le moment, si on veut on le modifiera dans le code.
