### ISSUE TITLE
[PLU] fiche d'info lien vers règlement

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#13]
Le clic sur le nom du règlement nous envoie **directement** sur le portail vers pydio qui nécessite une authentification. 
@MaelREBOUX ce lien n'est à mon avis pas utilisable tel quel.

La fiche d'info doit pointer vers le lien  **renseigné dans la table urba_fonc.plu_zone_urba dans le champ urlfic**; elle ne pointera peut  être pas sur pydio... (champ vide pour le moment - à renseigner de notre côté au moins pour les tests).
Il ne doit pas y avoir de lien en dur dans le code (je n'ai pas vu où c'était paramétré) ...

**Comment by jdenisgiguere** [comment]
Voir les options `fileServerUrl` et `fileRepositoryId` dans le fichier `config.json` de l'addon.

**Comment by catmorales** [comment]
Ok Merci jean-denis , nous allons tester

**Comment by MaelREBOUX** [comment]
J'ai publié 1 règlement littéral : celui de Pacé :

http://www.data.rennes-metropole.fr/fileadmin/user_upload/data/data_sig/urbanisme/plu/35210/35210_PLU_reglement_litteral_20140611.pdf

Le problème c'est que dans les données, actuellement urlfic est tout vide... Ce qui est normal. Je vois avec @lhamard pour remplir ça en dur pour test.

**Comment by MaelREBOUX** [comment]
@lhamard pourrais-tu jouer cette requête SQL STP ?

```sql
UPDATE urba_foncier.plu_zone_urba 
SET urlfic = 'http://www.data.rennes-metropole.fr/fileadmin/user_upload/data/data_sig/urbanisme/plu/35210/35210_PLU_reglement_litteral_20140611.pdf'
WHERE id_docurba LIKE '000035210%'
```

**Comment by lhamard** [comment]
Requête exécutée pour @MaelREBOUX 

La requête a été exécutée avec succés : 222 lignes modifiées. La requête a été exécutée en 125 ms.

**Comment by MaelREBOUX** [comment]
Merci. Faut maintenant modifier 

```
"zonesPluLayer": "urba_docs:plu_zone_urba",
"fileServerUrl": "http://www.data.rennes-metropole.fr/fileadmin/user_upload/data/data_sig/urbanisme/plu/",
```

**Comment by glavocat** [comment]
Modification faite dans le **config.json** pour la première ligne décrite ci-dessus.
Ainsi qu'une modification faite dans le **main.js**.
Les modifications ont été faites sur le serveur de test.

**Comment by MaelREBOUX** [comment]
PR https://github.com/sigrennesmetropole/addon_urbanisme/pull/15

**Comment by catmorales** [comment]
La redirection est bonne . 
Le clic sur le zonage nous renvoie bien vers le fichier dont le lien est stocké en base.
