### ISSUE TITLE
[PLU] Affichage et formatage de la date de validité

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#17]
La date dans l'attribut **datvalid** est au format AAAAMMJJ.
Il faut la transformer en JJ/MM/AAAA

**Comment by MaelREBOUX** [comment]
D'après le code : c'est pris directement dans les attributs WMS récupérés par interrogation de l'objet. Modif à faire dans main.js si j'ai bien suivi.

**Comment by fvanderbiest** [comment]
Fait avec 869caf7

![capture du 2016-12-22 13 57 40](https://cloud.githubusercontent.com/assets/265319/21426330/a076a04e-c84e-11e6-9311-d95c9b4952e1.png)
