### ISSUE TITLE
[PLU] Gérer les paires clé / valeur (ex : destdomi, typezone)

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#18]
L'attribut destdomi doit recevoir des valeur codées

00 : sans objet ou non encore définie dans le règlement
01 : habitat
02 : activité
03 : destination mixte habitat / activité
04 : loisirs et tourisme
05 : équipement public
07 : activité agricole
08 : espace naturel
09 : espace remarquable (littoral L146-6 / montagne L145-7)
10 : secteur de carrière
99 : autre

Comment on fait le mapping pour afficher un texte ?
Pour moi ce n'est pas possible dans les données. Sachant qu'en plus on doit diffuser ces données réglementaires on n'a pas de marge de manoeuvre.

Je propose donc de gérer un fichier json qui contiendra ce mapping. La réglementation pouvant évoluer je ne vois pas comment faire autrement à ce jour.

D'autres idées ?

**Comment by MaelREBOUX** [comment]
En attendant, je pose ça là

**cnig_reglmt_plu.json**

```json
/* 
ce fichier regroupe les listes de paires clé / valeurs
pour le règlement sur les documents d'urbanisme
*/
{
	"version": "1.0",
	"date": "2016-08-11",
	"destdomi": [{
		"code": "00",
		"label": "sans objet ou non encore définie dans le règlement"
	}, {
		"code": "01",
		"label": "habitat"
	}, {
    "code": "02",
		"label": "activité"
	}, {
    "code": "03",
		"label": "destination mixte habitat / activité"
	}, {
    "code": "04",
		"label": "loisirs et tourisme"
	}, {
    "code": "05",
		"label": "équipement public"
	}, {
    "code": "06",
		"label": ""
	}, {
    "code": "07",
		"label": "activité agricole"
	}, {
    "code": "08",
		"label": "espace naturel"
	}, {
	  "code": "09",
		"label": "espace remarquable (littoral L146-6 / montagne L145-7)"
	}, {
    "code": "10",
		"label": "secteur de carrière"
	}, {
    "code": "99",
		"label": "autre"
	}]
}
```

**Comment by MaelREBOUX** [comment]
Rajout des correspondances type zone simplifié suite demande SPEU.

Pour simplifier j'ai fait une PR #23 : à prendre ou à laisser.

**Comment by catmorales** [comment]
Le fichier json a été déployé mais il n'est pas pris en compte lors de la génération des fiches d'info. je pense qu'il doit manquer quelque chose dans le code.

**Comment by catmorales** [comment]
Après consultation de mes collègues, il s'avère que cette information sera présente en base prochainement car elle correspond à des domaines de valeur utilisés dans arcgis et entretenus par le service études urbaines. Donc  l'implémentaiton pourra se faire plutôt que par un fichier json au travers d'une vue en base ou vue geoserver.
Ce qui à mon avis simplifie la modification à faire dans le code.

**Comment by catmorales** [comment]
Dans la foulée, et pour simplifier, il serait pertinent de pouvoir paramétrer dans le config.json les champs à afficher dans la fiche d'info  et leurs paramètres css (couleur, police, taille, ...).

**Comment by fvanderbiest** [comment]
Avec c2b66a1 reformatage du document json + utf-8

**Comment by fvanderbiest** [comment]
> Le fichier json a été déployé mais il n'est pas pris en compte lors de la génération des fiches d'info

Oui, Mael n'a fait que fournir les données de mapping, mais n'a pas modifié le code pour qu'elles soient prises en compte.

Pour moi, si ce mapping doit etre pris en compte dans l'addon, il doit être intégré dans le config.json
C'est un peu une évolution, je ne considère pas ça comme un bug.

**Comment by MaelREBOUX** [comment]
En attendant un vrai mapping il faudrait faire un tooltip avec les valeurs de mapping sinon ça va être chaud la présentation en mars.

**Comment by fjacon** [comment]
note for myself : il s'agit d'un attribut du PLU.

**Comment by fvanderbiest** [comment]
Petite mise à jour avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/df305757799589e6d183c1f374210d4998bf6770
