### ISSUE TITLE
[PLU] formatage de la fenêtre d'infos zonage

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#19]
A gauche formatage actuel des infos.
A droite : formatage voulu.

![screenshot156](https://cloud.githubusercontent.com/assets/6370443/17621703/8957d642-6095-11e6-89ab-4f538a779e18.png)

Entre autres objectifs : avoir une fenêtre la plus petite possible.

**Comment by MaelREBOUX** [comment]
https://github.com/sigrennesmetropole/addon_urbanisme/pull/20

**Comment by MaelREBOUX** [comment]
A réviser à cause de #22

**Comment by MaelREBOUX** [comment]
Fait : commit fait dans la branche spécifique voir #20

**Comment by catmorales** [comment]
@fvanderbiest A merger si OK

**Comment by catmorales** [comment]
C'est bon
