### ISSUE TITLE
[PLU] Cas d'une commune sans PLU / Pas de zonage au clic

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#2]
Il faudra prendre en compte dans le développement le cas où il n'y pas de zonage plu  présent lors d'un clic dans la carte.

**Comment by jdenisgiguere** [comment]
À quoi pourrait ressembler la fenêtre Popup dans ce cas?

**Comment by MaelREBOUX** [comment]
Mettre simplement le texte suivant dans la popup :
"Pas de PLU numérique disponible pour cette commune."

Les raisons d'absence peuvent être nombreuses. Normalement les personnes qui en auraient besoin sont au courant de ces raisons.

**Comment by MaelREBOUX** [comment]
En attente déploiement pour test.

**Comment by jdenisgiguere** [comment]
À tester après l'intégration dans l'environnement de tests de la PR #14.

**Comment by MaelREBOUX** [comment]
faut merger pour qu'on teste. C'est bien @fvanderbiest qui fait les merge ?

**Comment by fjacon** [comment]
@fvanderbiest tu confirmes ?

**Comment by MaelREBOUX** [comment]
On attend toujours les merge des PR de la part de @fvanderbiest : le dev est en cours : on ne prend pas la responsabilité de merger.

**Comment by catmorales** [comment]
Je viens de tester cela pour moi c'est bon (clic sur Rennes):
![image](https://cloud.githubusercontent.com/assets/4659829/19075168/fc768a88-8a43-11e6-858a-d694602fc5a6.png)
