### ISSUE TITLE
[Cadastre - NRU] couche utilisée

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#25]
Afin de ne pas mélanger les couches applicatives de "cadastrapp" et "urbanisme", nous avosn choisi de créer une deuxième couche applicative `ref_cad:app_urbanisme_parcelle`. que j evais rajouter dans mon contexte urbanisme avec la couche zonage.
@pmauduit , pour paramétrer le module urbanisme avec cette nouvelle couche, il suffit juste de modifier https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/config.json#L7 ?

**Comment by pmauduit** [comment]
> @pmauduit , pour paramétrer le module urbanisme avec cette nouvelle couche, il suffit juste de modifier https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/config.json#L7 ?

Oui: le module urbanisme (plus précisément l'addon mapfishapp) est compilé complètement à part, puis intégré dans votre profil de configuration. Donc vous avez tout le coté client modifiable directement dans le profil de configuration.

**Comment by catmorales** [comment]
Ok c'est fait sur le serveur et ça marche; j'en ai profité pour rajouter les contextes en test  manquants:
*  urbanisme qui contient les couches nécessaires pur ce module
* topographie de surface pour le module rctr.

![image](https://cloud.githubusercontent.com/assets/4659829/19145598/f9005d6c-8baf-11e6-8d37-7127ba0597f6.png)

**Comment by catmorales** [comment]
et j'ai fait la modif ici également.
