### ISSUE TITLE
[NRU]Carte et Impression - on ne voit pas la parcelle interrogée

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#26]
La parcelle sélectionnée et interrogée pour produire la note de renseignement d'urbanisme n'est pas mise en évidence , ni dans la carte, ni dans l'impression.
Très gênant pour l'utilisateur.

**Comment by fvanderbiest** [comment]
Fait avec https://github.com/sigrennesmetropole/addon_urbanisme/commit/ec99ab7b76668e409403143b9a3a6acee69a2e56
