### ISSUE TITLE
[NRU] Impression - ne s'affiche que le fond

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#27]
Les données de la carte ne s'affichent pas dans l'impression. Seul le fond apparait. Même problème que 
https://github.com/camptocamp/georchestra-rennes-configuration/issues/459 ?

**Comment by fvanderbiest** [comment]
De plus il me semble que la carte imprimée n'est pas centrée sur la parcelle.

**Comment by fvanderbiest** [comment]
> Les données de la carte ne s'affichent pas dans l'impression.

Les couches sont bien envoyées au service d'impression par le code JS de l'addon.
Je soupçonne un problème de basic auth.

ex: https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/atlas/mapfishprintv3/config.yaml#L67

**Comment by fvanderbiest** [comment]
> Je soupçonne un problème de basic auth.

Même pas ...

**Comment by fvanderbiest** [comment]
> Même problème que
> camptocamp/georchestra-rennes-configuration#459 ?

En effet, bien vu !
Corrigé avec 55234e3
