### ISSUE TITLE
PDF NRU : pb sur adresse propriétaire

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#29]
L'adresse du proprio n'est pas correcte, cf capture d'écran.

![screenshot446](https://cloud.githubusercontent.com/assets/6370443/21675935/0978f066-d334-11e6-9cd3-9f2fa989c210.png)

**Comment by MaelREBOUX** [comment]
En profiter pour réaligner tous ces champs texte à gauche avec une marge.

**Comment by fvanderbiest** [comment]
> Il manque le nom de la commune dans l'adresse du propriétaire

Sur le PDF imprimé, je viens de comprendre ...

**Comment by fvanderbiest** [comment]
Pourtant le client l'envoie bien au serveur, mais avec beaucoup d'espaces ... ce qui pourrait expliquer que ce soit tronqué.

```json
adresseProprio
:
"6 RUE DE LA MARINE                                               56260 LARMOR-PLAGE              "
```

**Comment by fvanderbiest** [comment]
Est ce que ce sont les données source qui doivent être améliorées ou bien notre programme doit il supprimer des espaces dans les données ? Selon quelles règles ?

**Comment by fvanderbiest** [comment]
Actuellement il s'agit d'une concaténation de 3 champs, cf https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L69-L70

**Comment by catmorales** [comment]
Quand tu parles des données sources , tu parles bien du résultat de l'interrogation du  service issu de la webapp cadastre qui fournit cette information ?

**Comment by fvanderbiest** [comment]
Je parle en effet des champs `dlign4`, `dlign5` et `dlign6` qui composent l'adresse du propriétaire, en provenance du service `cadastrapp/getFIC`.

**Comment by catmorales** [comment]
Je préconise de faire la concaténation dans cette webapp . Ton avis @MaelREBOUX ?

**Comment by catmorales** [comment]
@fjacon relance car on a des réunions de présentation de ce module prévues en mars et il faut que ce soir résolu.
Merci d'avance

**Comment by MaelREBOUX** [comment]
@fvanderbiest je confirme usage dlign4 5 et 6 depuis la méthode getFIC de l'API cadastrapp. Avec du trim !

**Comment by fvanderbiest** [comment]
OK, fait avec https://github.com/sigrennesmetropole/addon_urbanisme/commit/a62e352b5e7e94ca39bd9db4a86d5fdc9952c0db

**Comment by catmorales** [comment]
à redéployer de notre côté

**Comment by fvanderbiest** [comment]
à fermer ?

**Comment by catmorales** [comment]
oui c'est bon
