### ISSUE TITLE
[RU] Mise en forme NRU web et print

### ISSUE THREAD

**Issue by jdenisgiguere** [sigrennesmetropole/addon_urbanisme#3]
Bonjour,

Voici une capture d'écran de la fenêtre d'affichage d'une note de renseignement d'urbanisme et un exemple de PDF généré.

Nous aimerions connaitre les éléments à ajouter ou à modifier pour répondre aux spécifications convenues.

Salutations cordiales,

![notes_screenshot](https://cloud.githubusercontent.com/assets/973241/15085289/73a3fd66-13a7-11e6-9b07-afdc9ee8a16c.png)

![notes_pdf_screenshot](https://cloud.githubusercontent.com/assets/973241/15085366/dd6e6e70-13a7-11e6-9e67-8d04d96844a5.png)

**Comment by catmorales** [comment]
En fait il manque  en bas, toutes les informations relatives au règlement lui-même (9)qui sont présentes à la parcelle dans la table renseign-urba.
cf https://docs.google.com/document/d/1egic2XPxlqX682K3_WF3h0yZQatEWjaQfV6NgRsYzxg/edit#heading=h.6al83oaha7dq

@MaelREBOUX  merci de confirmer ou compléter  les points suivants:
* pas besoin de rajouter la commune en clair  devant le code section par contre il faut le mettre complet avec le code commune et le préfixe de section du genre **350238000BX**
* surface calculée de la parcelle --> voir lapertinence de mettre 2 décimales (comme sur l'appli actuelle)

**Comment by MaelREBOUX** [comment]
Voici la liste des modifications :
- dans le tableau, rajouter une ligne avec le nom de la commune
- le code de section "000BX" doit être tout seul dans sa case et avec le code de préfixe de section soit 5 caractères en tout
- au-dessus du tableau, mettre l'identifiant complet du code de parcelle sans espaces (pour un éventuel copier-coller) : 35238000BX0285
- surface calculée / SIG : 1 décimale
- code de voie : changez en "Code Fantoir" + mettre le code en entier avec les zéros en préfixe (4 caractères, "0432")
- titre de la fenêtre : "Cadastrale" -> "cadastrale" pas de majuscule

**Comment by jdenisgiguere** [comment]
- L'exemple retenu n'illustre pas bien le chargement du champ libelle. La prochaine capture sera plus parlante. :-)

- Il y aura une ligne pour le nom de la commune au-dessus du code de section (ce sera la première ligne)

- Il y a trois interprétations du code de section:
 1. cgecommune + ccosec + ccopre (ex. 350238000BX)
 2. ccosec + ccopre même si ccosec == "000" (ex. 000BX)
 3. règle présentée dans le document de spécification: 
> si  ccopre <> “000” afficher ccopre + ccosec
> => 073AX
> sinon afficher uniquement ccosec
> => BX
Merci de me confirmer votre préférence.

- Nous garderons une seule décimale pour surface calculée (specs + @MaelREBOUX ).

- Nous ajouterons un 0 au code de vois si la réponse ne contient que 3 caractères.

-  Le titre sera Réglementation applicable à la parcelle **c**adastrale


Si certaines interprétations sont inexactes, merci de m'en aviser.


Cordialement,

**Comment by jdenisgiguere** [comment]
Voici un nouveau PDF. 

Vos commentaires sont les bienvenus.

[note.pdf](https://github.com/sigrennesmetropole/addon_urbanisme/files/257101/note.pdf)

**Comment by MaelREBOUX** [comment]
Sur le ccopre, j'y ai justement réfléchi entre-temps : on reste sur les specs et donc la proposition iii (affiche du préfixe de section uniquement s'il y a besoin).

Penser aux petites corrections vues plus haut.

Il y a des choses à faire côté mise en forme / mise en page.
Si possible, mettre un tableau sans bordure 1 colonne 1 ligne en haut.
Cellule de gauche = logo Rennes Métropole (voir avec @catmorales pour fourniture d'une url /!\)
Cellule de droite = "Réglementation applicable à la parcelle cadastrale XXXXXXX"

En fin de document, rajouter un pied de page contenant la phrase "Un service fourni par le SIG de Rennes Métropole".

**Comment by jdenisgiguere** [comment]
Bonjour @MaelREBOUX ,

Je ne saisis pas très bien où devrait se retrouver le tableau sans bordure. J'aurais aussi besoin de plus de détail quant à la taille des cellules. Si vous pouvez me fournir un croquis, j'ajusterai le gabarit en conséquence.

Les éléments suivants ont été corrigés au meilleur de ma compréhension.

- La liste des libelles est affichée sous le tableau
- Le tableau commence par une rangée indiquant le nom de la commune
- Le code de section continent uniquement les lettres si le préfixe est 000
 - Le code Fantoir possède toujours 4 caractères
- Le mot cadastrale apparait avec une lettre minuscule dans le titre.
- Le pied de page en fin de document contient la mention _Un service fourni par le SIG de Rennes Métropole_

N'hésitez pas à m'indiquer si certaines corrections semblent incomplètes.

Salutations cordiales,

**Comment by MaelREBOUX** [comment]
En fait, si je devais formater à l'ancienne avec des tableaux HTML / XSL, ça donnerait ce qui est en pj.

[nru.docx](https://github.com/sigrennesmetropole/addon_urbanisme/files/261752/nru.docx)

C'est du YAML la mise en page ?

**Comment by jdenisgiguere** [comment]
Merci @MaelREBOUX !

L'impression de la page se fait via MapFishPrint 3. La mise en page est un gabarit JasperReport.

**Comment by MaelREBOUX** [comment]
Comment est triée la liste des "zonages" qui impacte la parcelle ? C'est quoi la requête qui est envoyée sur la table ?

**Comment by jdenisgiguere** [comment]
Présentement, il n'y a pas de tri. Je serai heureux d'implémenter un ordre qui vous semble logique.

**Comment by MaelREBOUX** [comment]
Les personnes (instructeurs) qui utiliseront principalement ce document disposent dans leur logiciel actuel d'un regroupement par très grandes catégories.
J'ai trouvé les éléments dans la base de données pour le faire.
Je vous rapporte ces éléments mardi prochain (wd de 3 j).

**Comment by MaelREBOUX** [comment]
Il m'avait manqué 1/2 h vendredi pour terminer de vous répondre.

Nous avons la possibilité de réalisé un groupement des différents enregistrements identique à celui réalisé dans le client lourd "droit des sols". Tout est dispo en base.
@catmorales vous fournit à suivre un dump de la table **param_theme** à utiliser en plus de la table **renseign_urba**.

Voici la requête à exécuter pour 1 parcelle cadastrale :

```sql
SELECT renseign_urba.* , param_theme.ventilation_ddc
FROM app_plu.renseign_urba FULL JOIN app_plu.param_theme on renseign_urba.nom_theme = param_theme.nom 
WHERE id_parc = '350352000AE0054'
```
Le regroupement de mise en forme par blocs est donc à opérer sur l'attribut **ventilation_ddc** (ventilation droit de cité).

La **correspondance entre ces codes et le libellé à afficher, dans cet ordre** :

1. ZON -> Dispositions d'urbanisme
2. SUP -> Servitudes d'utilités publiques
3. SAU -> Autres servitudes
4. PRE -> Préemption
5. OPE -> Opérations
6. PAR -> Participations
7. LOT -> Lotissement
8. TAX -> Taxes d'aménagement

**Comment by MaelREBOUX** [comment]
Pour info / mémo :

'TAX';307964
'SAU';282984
'ZON';220336
'SUP';196906
'PRE';64931
'OPE';12339
'PAR';9952
'LOT';6432

**Comment by catmorales** [comment]
Dum envoyé par mail ce jour  @jdenisgiguere

**Comment by jdenisgiguere** [comment]
Bien reçu!

Merci pour les précisions.

**Comment by jdenisgiguere** [comment]
@catmorales , est-ce possible d'avoir l'URL du logo pour le rapport PDF  (c. f.) https://github.com/sigrennesmetropole/addon_urbanisme/files/261770/nru.docx ?

**Comment by catmorales** [comment]
En attendant d'avoir un site plus "officiel" , j'ai mis les logos ici, j'espère que cela te convient:
https://github.com/sigrennesmetropole/images/blob/master/logos/RM_quadriNOIR.png
https://github.com/sigrennesmetropole/images/blob/master/logos/SIG_RM.png
@MaelREBOUX faut-il que l'on mette quelque chose par rapport à la licence  pour les logos ?
Il faudra que cette url soit paramétrable et puisse être modifiée par l'administrateur.
Merci

**Comment by fvanderbiest** [comment]
> Il faudra que cette url soit paramétrable et puisse être modifiée par l'administrateur

Ce sera dans le template Jasper, ce qui devrait répondre au besoin...

**Comment by MaelREBOUX** [comment]
En attente déploiement pour test.

**Comment by fjacon** [comment]
Déployé ? et testé ?

**Comment by MaelREBOUX** [comment]
oui mais on ne peut pas tester davantage à cause de #10 qui est bloquant. En attente des corrections de votre côté.

**Comment by catmorales** [comment]
en +
Demande d'explications sur la modification du template jasper.

**Comment by pmauduit** [comment]
> en +
> Demande d'explications sur la modification du template jasper.

Les fichiers JRXML présents ici: https://github.com/georchestra/georchestra/tree/master/atlas/src/main/resources/atlas

peuvent être surchargés dans votre profil de configuration:

https://github.com/camptocamp/georchestra-rennes-configuration/tree/master/atlas/WEB-INF/classes/atlas

les fichiers jrxml sont en réalité des fichiers XML qu'il peut être plus facile d'éditer avec un outil basé sur Eclipse (Jasper studio): http://community.jaspersoft.com/project/jaspersoft-studio. Ci-après une capture d'écran:

![jasperstudio](https://cloud.githubusercontent.com/assets/594335/19112530/a34eabb2-8b05-11e6-8148-3b3ff8963e7b.png)

**Comment by catmorales** [comment]
OK Merci Pierre , il faudra que l'on reprenne cela en même temps que les impressions de mapfishapp.

**Comment by catmorales** [comment]
@tester de notre côté

**Comment by catmorales** [comment]
Je ferme ce ticket car les problèmes sont résolus. 
Il reste juste l aparamétrage du jasper report à faire de notre côté.
