### ISSUE TITLE
Comportement boutons  urbanisme sur les couches fonctionnelles

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#30]
Reproduction du bug sur la plateforme de test:
1- je me connecte avec le contexte par défaut uniquement
2 - je charge l'addon urbanisme
3-j'ai oublié de rajouter le contexte urbanisme,  je le rajoute  maintenant à ma carte (il contien,t les 2 couches fonctionnelles du module  --> les boutons ne sont pas chargés sur les couches fonctionnelles , il faut faire un rechargement de mapfishapp pour les voir apparaître

**Comment by catmorales** [comment]
@fjacon relance cat iona des réunions de présentation de ce module prévues en mars et il faut que ce soir résolu.
Merci d'avance

**Comment by fjacon** [comment]
Pour la démonstration, ce ticket ne me semble pas prioritaire. Il est relativement facile de contourner le problème. Je préfère attendre le retour de François. 
@catmorales est-ce OK pour toi ?

**Comment by catmorales** [comment]
ok on attend le retour de François pour ce ticket

**Comment by fvanderbiest** [comment]
Je relis en même temps les specs de cette fonction ... https://docs.google.com/document/d/1egic2XPxlqX682K3_WF3h0yZQatEWjaQfV6NgRsYzxg/edit#heading=h.ak7r812whbow

**Comment by fvanderbiest** [comment]
Pour mémoire, les specs indiquaient:

Dès que l’addon sera chargé :
 * toutes les couches déjà chargées seront examinées. Si l’une correspond à celles fournies dans la configuration, l’addon modifiera sa barre d’outil en propre de manière à y ajouter une icone (“i” orange par exemple) correspondant à un outil d’interrogation métier 
 * si une de ces couches est chargée a posteriori, ce nouveau (i) sera déjà présent.

Si cela n’est techniquement pas possible : l’outil sera présent dans le menu actions (car généré post chargement de l’addon et des couches).

**Comment by fvanderbiest** [comment]
Par ailleurs le [commit de Pierre G.](https://github.com/sigrennesmetropole/addon_urbanisme/pull/33/files) a supprimé le premier comportement ("toutes les couches déjà chargées seront examinées. Si l’une correspond à celles fournies dans la configuration, l’addon modifiera sa barre d’outil en propre de manière à y ajouter une icone (“i” orange par exemple) correspondant à un outil d’interrogation métier")

**Comment by catmorales** [comment]
Effectivement, nous pensions dans un premier temps que l'on conserverait  les 2 fonctionnements mais il s'avère qu'à l'usage le seul fonctionnement "barre d'outils" fait par Pierre est très pratique côté utilisateur car il correspond à l'ergonomie de cadastrapp ; les deux  étant utilisés simultanément la plupart du temps.
Et il n'est plus utile de disposer de la fonction (i) au niveau de la couche.

Mais le travail qui a été fait pour l'implémentation du (i) au niveau de la couche est à conserver pour d'autres usages à venir que nous n'avons pas encore définis.

En effet, la substitution du i générique par un i spécifique permettant d'ouvrir une fiche d'info html enrichie reste un besoin important: ex à venir probablement sur les points d'apport volontaires et déchets ménagers

**Comment by catmorales** [comment]
Par conséquent on peut fermer ce ticket
