### ISSUE TITLE
[PLU] Rajouter lien vers le ZIP du dossier du document d'urbanisme

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#31]
Dans la fiche d'info rajouter une nouvelle ligne avec un lien amenant vers le ZIP contenant toutes les pièces.

Problème : cette info n'est pas dans plu_zone_urba (cette couche) mais dans plu_document_urba.
Mais la valeur est facilement déductible des infos et est déjà calculée lors de la mise en production des données.

ex d'url : 'http://public.sig.rennesmetropole.fr/ressources/donnees/plu/35058/35058_PLU_20111215.zip'

concaténation de 
'http://public.sig.rennesmetropole.fr/ressources/donnees/plu/' 
+ substr(nomfic, 0, 5) 
+ '/' +  substr(nomfic, 0, 5) 
+ '_PLU_' + datvalid 
+ '.zip'

**Comment by fvanderbiest** [comment]
Fait avec 54d20db

**Comment by catmorales** [comment]
Super !!! C'est très attendu.

**Comment by fvanderbiest** [comment]
Reporté sur config test avec https://github.com/camptocamp/georchestra-rennes-configuration/commit/a0bd8d94f260e1da41cd94b2744b9890ebd5036f

**Comment by catmorales** [comment]
Je viens de redéployer et tester. 
C'est OK pour nous. Je ferme.
