### ISSUE TITLE
Modifier requête renseign_urba JOIN param_theme

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#34]
Pour des contraintes de différenciation données en élaboration / données en production il faut modifier la requête suivante :
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/main/java/org/georchestra/urbanisme/RenseignUrbaBackend.java#L85-L101

pour différencier les schémas :
- table = urba_foncier.renseign_urba
- tableTheme = app_plu.param_theme

**Comment by fvanderbiest** [comment]
Je ne comprends pas bien la demande: qui doit faire quoi ici ?

**Comment by catmorales** [comment]
J'explique le problème que nous avons rencontré :
* la table renseign_urba a changé de schéma en base et a été déplacée de app_plu vers urba_foncier mais ce n'est pas le cas de  la table param_theme qui est toujours dans le schéma app_plu ,
*  j'ai donc  modifié le fichier properties en conséquence https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/urbanisme/urbanisme.properties#L4 sans modifier  la valeur de app_plu.param_theme 
=> cela ne fonctionnait pas , les données ne pouvaient plus s'afficher et il ya vaiyt une erreur 500 de mémoire
* nous avons donc créée une vue pour la tableTheme=urba_foncier.v_croiseplu_param_theme temporairement pour rétablir la situation.

Mais cettevue n'a pas vocation à perdurer , il nous faudra donc bien conserver les 2 tables dans des schémas différents, ce qui ne fonctionne pas actuellement.

Merci de modifier le code pour autoriser ce fonctionnement des 2 tables dans 2 schémas différents.

**Comment by MaelREBOUX** [comment]
Suite à la vérification faite sur les données en #45 je pense qu'on peut fermer ce ticket car on tape bien les données en production.
@catmorales  ok ?

**Comment by catmorales** [comment]
> car on tape bien les données en production.
Je ne vois pas le rapport ...

On peut fermer ce ticket et je modifierai à nouveau la table parm_theme (quand les autres tickets seront résolus) afin de vérifier qu'il y a réellement un problème si les 2 schémas sont différents, car quand nous avons fait le test , il y avait un autre problème.
Si il y a réellement un problème , je rouvrirai un ticket à ce sujet.
