### ISSUE TITLE
[NRU]les données des noms de propriétaires ne s'affichent plus 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#35]
Si possible, merci de corriger cela avant jeudi matin (2ème session de nos présentations) mais ne pas toucher à la plateforme de test cet après-midi car nous serons en pleine démo à partir de 14h00.

Pourtant, le compte avec lequel je me suis connecté est bien autorisé. D'ailleurs on voit le compte propriétaire...
![image](https://cloud.githubusercontent.com/assets/4659829/23650213/9e1e4bfe-0321-11e7-9fba-ffac476f1df2.png)

**Comment by fvanderbiest** [comment]
Vous dites "les données des noms de propriétaires ne s'affichent plus".

Parce que ça a marché à un moment ? Comment est-ce possible si ce n'est un changement dans la fourniture des données source par cadastrapp ?

Je vois qu'avant c'était fourni par `ddenom` via https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L68

**Comment by fvanderbiest** [comment]
Et puis maintenant c'est un tableau de noms de propriétaires... donc comment on gère ce nouveau cas ?
Pour moi ce n'est pas un bug... même si fonctionnellement "ca ne marche plus pour vous".

**Comment by fvanderbiest** [comment]
@pmauduit me dit que vous déployez cadastrapp sur une branche master, ce qui introduit potentiellement des changements fonctionnels ou d'API de ce genre. Ca me semble risqué.

Est-ce qu'on pourrait imaginer déployer plutot une branche stable sur cadastrapp ?

**Comment by catmorales** [comment]
@pmauduit me dit que vous déployez cadastrapp sur une branche master, ce qui introduit potentiellement des changements fonctionnels ou d'API de ce genre.

Je n'ai pas redéployé cadastrapp depuis que la version est sortie, et le prochain redéploiement se fera sur la version stable qui existe maintenant.
 Le dernier war en place date du 04 novembre:
![image](https://cloud.githubusercontent.com/assets/4659829/23958585/db9616c4-09a2-11e7-9f2e-81b856685e63.png)

**Comment by pmauduit** [comment]
Contrairement à ce qui est fait dans georchestra qui utilise des branches, cadastrapp taggue ses versions en utilisant des tags git (la dernière étant 1.3), mais à ma connaissance c'est la branche master qui est construite chez vous.

**Comment by catmorales** [comment]
Effectivement car la dernière fois que j'ai déployé cadastrapp la release n'existait pas

**Comment by MaelREBOUX** [comment]
Bonjour,

Je peux confirmer pour avoir participer à la release 1.3 que à la date du 04/11/2016 il y a eu un gel des devs pour pouvoir sortir la version 1.3 de cadastrapp. Le déploiement du 04/11/2016 chez nous m'a servi à valider les dernières corrections pour la v 1.3.

Donc, comme Catherine n'a pas redéployé depuis cette date, même si c'était sur master c'est fonctionnellement la 1.3. cf https://github.com/georchestra/cadastrapp/commits/Cadastrapp-v1.3

Je vais (j'espère) faire les préliminaires pour la 1.4 très bientôt. @catmorales passera justement sur la branche 1.4 pour le prochain déploiement.

**Comment by MaelREBOUX** [comment]
Ha oui : et il y a tjs eu des tableaux JSON pour les proprios, triés par l'attribut dnulp pour être conforme au contenu des micro-fiches DGFiP.

Si n proprio :  1 app_nom_usag par ligne

Exemple 

```json
[

    {
        "dnulp": "01",
        "comptecommunal": "350032M00XXX",
        "app_nom_usage": "M XXXX XXXXX",
        "dlign3": "                              ",
        "dlign4": "53 RUE DU PATIS DES NOES          ",
        "dlign5": "                              ",
        "dlign6": "35230 SAINT-ARMEL               ",
        "dldnss": "35 NOYAL-CHATILLON-SUR-SEICHE                             ",
        "jdatnss": "23/03/1952",
        "ccodro": "P",
        "ccodro_lib": "PROPRIETAIRE"
    },
    {
        "dnulp": "02",
        "comptecommunal": "350032M00XXXX",
        "app_nom_usage": "MME XXXX XXX",
        "dlign3": "                              ",
        "dlign4": "53 RUE DU PATIS DES NOES          ",
        "dlign5": "                              ",
        "dlign6": "35230 SAINT-ARMEL               ",
        "dldnss": "35 GUERCHE-DE-BRETAGNE (LA)                               ",
        "jdatnss": "04/01/1953",
        "ccodro": "P",
        "ccodro_lib": "PROPRIETAIRE"
    }

]
```

**Comment by fvanderbiest** [comment]
Je vais modifier en conséquence l'addon, mais je confirme que les specs indiquaient bien l'usage de `ddenom` du service `getFIC` pour le nom des propriétaires, alors que maintenant cette information est fournie par le service `getInfoBulle` dont le retour est par ex.:
```json
{
    "parcelle": "350238000EX0057",
    "cgocommune": "350238",
    "dnupla": "57",
    "ccopre": "",
    "ccosec": "EX",
    "surfc": 1196.0,
    "libcom": "RENNES",
    "dcntpa": 1205,
    "dnvoiri": "    ",
    "dindic": " ",
    "cconvo": "RUE ",
    "dvoilib": "DE L ANGOUMOIS",
    "proprietaires": [{
        "app_nom_usage": "ASSOC SYND RES MONTBARROT ILOT 21"
    }],
    "comptecommunal": "350238*06148",
    "dcntpa_sum": 3438,
    "sigcal_sum": 3442.0
}
```
![capture du 2017-03-17 11-29-05](https://cloud.githubusercontent.com/assets/265319/24039321/0b950d40-0b05-11e7-80df-3a15e5d35d84.png)

**Comment by MaelREBOUX** [comment]
OK : j'ai compris ta question.

La version 1.3 de cadatrapp introduit un changement liée à l'évolution de la réglementation.
En version courte : **ddenom est devenu app_nom_usage** (Prise en compte du nom d'usage et du nom de naissance à la place du nom marital) cf https://github.com/georchestra/cadastrapp/wiki/Releases#v-13-novembre-2016

Donc je te confirme qu'il faut bien utiliser getFIC?parcelle=XXXX&onglet=1  et juste renommer ddenom en app_nom_usage
https://github.com/sigrennesmetropole/addon_urbanisme/blob/7fecdb8f3acd526f3b9fcba7c9ab63a069660f3b/src/addon/urbanisme/js/main.js#L68

**Comment by fvanderbiest** [comment]
> juste renommer ddenom en app_nom_usage

Un peu plus en fait:  ff1dd41
J'update votre config sur la branche `test` et je déploie sur la machine de `test` dans la foulée

**Comment by catmorales** [comment]
Merci François,
Une petite question pour que je comprenne bien:

Si tu récupères le compte propriétaire depuis getFIC et le nom des propriétaires depuis getInfoBulle, ne risque t-il pas d'y avoir une incohérence  ?

**Comment by fvanderbiest** [comment]
> Si tu récupères le compte propriétaire depuis getFIC et le nom des propriétaires depuis getInfoBulle, ne risque t-il pas d'y avoir une incohérence ?

Je ne sais pas ;-)

Ca semble marcher, ex:
![capture du 2017-03-17 15-34-34](https://cloud.githubusercontent.com/assets/265319/24047858/4e2d8a8e-0b27-11e7-961e-43640148bdec.png)

**Comment by fvanderbiest** [comment]
> je déploie sur la machine de test dans la foulée

Fait.

**Comment by MaelREBOUX** [comment]
Euh : tu confirmes que que avec cette ligne 
```noteRecord.set("nomProprio", infoBulleJson.proprietaires);```

Tu utilises getInfobulle pour récupérer le nom des proprios ? Pcq il vaut mieux utiliser getFIC

Et pour la mise en forme tu pourrais pas faire la boucle plutôt dans la cellule du tableau (<td>) : ça serait plus propre pcq on peut avoir jusque 8 propriétaires.

**Comment by fvanderbiest** [comment]
> Tu utilises getInfobulle pour récupérer le nom des proprios ? 

oui

> Pcq il vaut mieux utiliser getFIC

Information pas présente dans la réponse de ce service à ma connaissance.

**Comment by MaelREBOUX** [comment]
si si : cf ce que j'ai mis plus haut : https://github.com/sigrennesmetropole/addon_urbanisme/issues/35#issuecomment-286809012  (y a du trim à faire)

tu appelles si tu veux ?

**Comment by MaelREBOUX** [comment]
la suite dans #43
