### ISSUE TITLE
[NRU] Modifications diverses sur les infos affichées

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#38]
Concerne l'affichage web et print

- adresse du terrain -> adresse cadastrale
- code Rivoli (Fantoir) -> ne plus afficher + confusion surface SIG / contenance DGFiP / code RIVOLI ()
- surface cadastrale (m²) -> contenance DGFiP  (m²)
- supprimer les adresses des proprios. 2 raisons :
  - pas utile du tout sur une NRU -> outil cadastre dédié
  - 1 adresse par propriétaire -> pas géré actuellement

**Comment by MaelREBOUX** [comment]
getFIC onglet 0

dcntpa :1268 => contenance DGFiP
surfc :1289 => surface calculée
ccoriv :"0022" => code rivoli

**Comment by MaelREBOUX** [comment]
Tous les proprios dans une cellule :
- fait (à tester) sur web
- comment faire en print sans utiiser Jasper...

**Comment by MaelREBOUX** [comment]
Suppression des adresses des proprios :
- fait (à tester) sur web
- comment faire en print sans utiliser Jasper...

**Comment by MaelREBOUX** [comment]
git branch issue-38
git reset --hard HEAD~4
git checkout issue-38
git push --set-upstream origin issue-38

=> https://github.com/sigrennesmetropole/addon_urbanisme/pull/41

**Comment by MaelREBOUX** [comment]
OK mode web mais pas OK mode print : les modif n'apparaissent pas (encore) même après avoir maj les fichiers.
@catmorales vérifie datadir.

**Comment by catmorales** [comment]
datadir vérifié

**Comment by catmorales** [comment]
problème de configuration des impressions qui n'a pas été modifié suite aux changements

**Comment by catmorales** [comment]
Impression corrigé mais il manque encore la valeur de la surface calculée.
