### ISSUE TITLE
WMS zones PLU

### ISSUE THREAD

**Issue by jdenisgiguere** [sigrennesmetropole/addon_urbanisme#4]
Pour finaliser le développement de l'addon, j'aurais besoin d'un accès à la couche WMS des zones de PLU. 

Est-ce possible de rendre la couche disponible via l'extranet https://portail.sig.rennesmetropole.fr/ ?

**Comment by catmorales** [comment]
Je regarde

**Comment by catmorales** [comment]
@jdenisgiguere On va la publier , on te tient au courant dès que ce sera prêt en Extranet.

**Comment by catmorales** [comment]
@jdenisgiguere c'est fait la couche est publiée sur l'extranet:
```
...
<Layer queryable="1" opaque="0"><Name>urba_fonc:plu_zone_urba</Name><Title>Zonages des plans locaux d'urbanisme sur Rennes Métropole</Title><Abstract>TO DO</Abstract><KeywordList><Keyword>plu_zone_urba</Keyword><Keyword>features</Keyword>
...
```

**Comment by jdenisgiguere** [comment]
@catmorales , est-ce prévu que la couche ait les champs

- libelong
- urlfic
- destdomi
- datvalid

disponibles pour remplir le gabarit de la fiche d'information?

Pour référence, voir le tableau des sources de données, section **Fiche d’informations “zonage du PLU”**  dans le cahier des charges.

**Comment by catmorales** [comment]
>disponibles

Je suppose que tu veux dire "remplis"  car les champs sont bien présents . Il y a quelques données sur les zones Z1315 à Z1381 (idzone)- commune 35139 (Laillé)

**Comment by jdenisgiguere** [comment]
Merci pour la précision, j'examine mieux la réponse XML maintenant.

- `urlfic` est pésent, mais peut être vide.  Je ne générerai pas l'URL si l'information n'est pas présente.
- `destdomi` est un code numérique (ex. 3, 8) comme attendu dans les spécifications. Pouvez-vous me fournir la table de correspondance?
- `datvalid` est dans la réponse, mais peut être vide.

`libelong` n'est pas présent dans la réponse xml.

**Comment by catmorales** [comment]
Je ne sais pas si ça peut t'aider: mais voici déjà  les caractéristiques des champs en base:
```

CREATE TABLE urba_foncier.plu_zone_urba
(
  objectid integer NOT NULL,
  id_docurba character varying(17),
  libelle character varying(12) NOT NULL,
  libelong character varying(254),
  typezone character varying(3) NOT NULL,
  destdomi character varying(2),
  nomfic character varying(80),
  urlfic character varying(254),
  datvalid character varying(8),
  idzone character varying(10) NOT NULL,
  gdb_geomattr_data bytea,
  shape geometry,

```

**Comment by catmorales** [comment]
En effet libelong est vide partout, mais il semble que ce soit  normal pour le moment, les gestionnaires de données n'ont pas encore remplis ces valeurs (service urbanisme).

urlfic sera une url et sera rempli quand nous aurons un site pour stocker le règlement, ce qui n'est pas encore le cas.

ci-joint ce que je vois sur le jeu de données en base pour que tu puisses comparer.

![image](https://cloud.githubusercontent.com/assets/4659829/15254281/4bb0502c-1936-11e6-8c95-e94fe2fe4a63.png)

**Comment by catmorales** [comment]
Pour destdomi, je me renseignerai lundi. Bon Week end !

**Comment by jdenisgiguere** [comment]
Merci Catherine! 
Bonne fin de semaine!

**Comment by MaelREBOUX** [comment]
On laisse tomber l'affichage de l'attribut `destdomi` pour le moment. 2 raisons :
- classification entre local / national pas cohérente
- volonté de renvoyer vers la lecture intégral du règlement

**Comment by MaelREBOUX** [comment]
Et on n'a pas répondu mais on a bien publié la couche des zonages en WMS il y a qqs j :  urba_fonc:plu_zone_urba

**Comment by MaelREBOUX** [comment]
vous aurez noté que la couche est urba_docs:plu_zone_urba (mauvais classement de ma part avant).
cf https://github.com/sigrennesmetropole/addon_urbanisme/commit/f50a1e455bbabccf6171aeb388df6f92e717a19f

Et que j'ai rempli avec des données normalement cohérentes sur Pacé
cf #16 

je ferme ce ticket.
