### ISSUE TITLE
[NRU] La surface SIG peut être fournie par getFIC

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#40]
Depuis la v1.3 de cadastrapp la surface SIG est fournie via GetFIC onglet 0 attribut 'surfc'

Modifier la source de données dans main.js

**Comment by MaelREBOUX** [comment]
Je me suis inspiré de la ligne qui récupère la contenance DGFiP. En espérant que ça fonctionne .

=> PR 42

**Comment by MaelREBOUX** [comment]
En lien avec #43 : @fvanderbiest si tu confirmes que l'info vient de getFIC : fermer ce ticket SVP.

**Comment by fvanderbiest** [comment]
Non, actuellement 'surfc' vient de getParcelle sans paramètre onglet.
