### ISSUE TITLE
[NRU] Noms proprio sont fournis par getFIC

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#43]

**Comment by catmorales** [comment]
François, nous voulons que tu utilises getFIC au lieu de getInfoBulle car il est plus adapté et plus fiable. On ne comprend pas pourquoi tu n'as pas trouvé l'info dans getFIC car app_nom_usage y est bien présent en lieu et place de ddenom effectivement, les specs datent de 2015 ...).

En Effet,
`https://portail.sig.rennesmetropole.fr/cadastrapp/services/getFIC?parcelle=350238000AB0012&onglet=1`   rend bien:
```
[{
    "dnulp": "01",
    "comptecommunal": "350238*01526",
    **"app_nom_usage": "4 RUE ROBELIN(LES COPS)",**
    "dlign3": "                              ",
    "dlign4": "4 RUE ROBELIN                    ",
    "dlign5": "                              ",
    "dlign6": "35000 RENNES                    ",
    "dldnss": "                                                          ",
    "jdatnss": "          ",
    "ccodro": "P",
    "ccodro_lib": "PROPRIETAIRE"
}, {
    "dnulp": "02",
    "comptecommunal": "350238*01526",
    **"app_nom_usage": "M TESNIERES MARCEL",**
    "dlign3": "                              ",
    "dlign4": "14 RUE DE TREGAIN                 ",
    "dlign5": "                              ",
    "dlign6": "35700 RENNES                    ",
    "dldnss": "                                                          ",
    "jdatnss": "00/00/0000",
    "ccodro": "S",
    "ccodro_lib": "SYNDIC DE COPROPRIETE"
}]
```

**Comment by fvanderbiest** [comment]
Fait avec	30a76bc, votre config a été mise à jour, branche test, déployé sur test.

**Comment by MaelREBOUX** [comment]
Okay.

Donc pour moi il ne devrait plus y avoir de recours à getInfoBulle.
Pour le moment il y a tjs une requête qui part vers cette méthode mais normalement on n'y récupère plus rien :
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L57-L61
et
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L746-L748

Tu confirmes ?

**Comment by fvanderbiest** [comment]
> Donc pour moi il ne devrait plus y avoir de recours à getInfoBulle.

Oui, je supprime cet appel avec af38789
