### ISSUE TITLE
[NRU] contenance DGFiP tronquée à la dizaine de milliers

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#44]
Exemple sur parcelle  350024000AP0033

contenance DGFiP = 9624
surface SIG = 19649.0

**Comment by catmorales** [comment]
@fvanderbiest , merci de corriger ce point car nous affichons les 2 valeurs de surface et il ya une incohérence du coup.

**Comment by fvanderbiest** [comment]
Il me semble que c'est traité par https://github.com/sigrennesmetropole/addon_urbanisme/pull/42/files
On peut fermer ?

**Comment by MaelREBOUX** [comment]
Non : ça ne va pas 
![screenshot621](https://cloud.githubusercontent.com/assets/6370443/24363077/fadc64c8-130e-11e7-8db9-0848aaca835d.png)

**Comment by catmorales** [comment]
je confime le champ surface calculée ne donne pas la bonne valeur:
![image](https://cloud.githubusercontent.com/assets/4659829/24401301/2286cdec-13b4-11e7-8da8-4bb3684da293.png)

**Comment by catmorales** [comment]
https://portail.sig.rennesmetropole.fr/cadastrapp/services/getFIC?parcelle=350024000BE0448&onglet=0 donne
```
[  
   {  
      "cgocommune":"350024",
      "libcom":"BETTON",
      "ccopre":"",
      "ccosec":"BE",
      "dnupla":"448",
      "ccoriv":"0214",
      "dnvoiri":"18",
      "dindic":" ",
      "cconvo":"RUE ",
      "dvoilib":"D'HELSINKI",
      "dcntpa":5761,
      "surfc":5758.0,
      "gparbat":"1",
      "gurbpa":" "
   }
]

```

donc on devrait avoir la valeur 5758 ou 5758.0
la requête prend elle en compte la valeur onglet = 0 et non pas onglet =1 ?

**Comment by fvanderbiest** [comment]
> la requête prend elle en compte la valeur onglet = 0 et non pas onglet =1 ?

C'est nouveau cette notion d'onglet ? Je n'y vois aucune référence dans les specs de l'addon urbanisme.
Actuellement onglet = 1

**Comment by fvanderbiest** [comment]
> Actuellement onglet = 1

En fait non, il était non défini.

**Comment by fvanderbiest** [comment]
Donc si je comprends bien, `surfc` (surface sig) et `dcntpa` (contenance) doivent venir de `getFIC?parcelle=350024000BE0448&onglet=0`

Actuellement cette requête part avec le paramètre onglet = 1 afin d'obtenir notamment les noms des propriétaires et l'adresse.

**Comment by MaelREBOUX** [comment]
oui : en provenance de getFIC?onglet=0 ```surfc``` = surface SIG calculée et ```dcntpa``` = contenance DGFiP

**Comment by catmorales** [comment]
Je reviens sur ce ticket qui n'est pas résolu . 
Correction faite sur notre profil de configuration:

noteRecord.set("contenanceDGFiP", ("0000" + parcelleRecord.get("dcntpa")).slice(-4));
noteRecord.set("surfaceSIG", ("0000" + parcelleRecord.get("surfc")).slice(-4));
 
changé pour

 noteRecord.set("contenanceDGFiP", parcelleRecord.get("dcntpa"));
 noteRecord.set("surfaceSIG", parcelleRecord.get("surfc"));
 
En effet , le fait de limiter à 4 car. faussait les résultats : les parcelles très grandes étaient tronquées !
Je vous laisse corriger sur ce dépot .

**Comment by catmorales** [comment]
Par contre le résultat ne rend toujours rien pour la surface calculée, sans doute car 
![image](https://cloud.githubusercontent.com/assets/4659829/25273801/b05036cc-268d-11e7-879a-39baf7e8d96f.png)
 `https://portail-test.sig.rennesmetropole.fr/cadastrapp/services/getFIC?_dc=1492770344512&parcelle=350024000AI0073&onglet=1`
ne rend pas cette valeur.

Par contre ,
`https://portail-test.sig.rennesmetropole.fr/cadastrapp/services/getFIC?_dc=1492770344512&parcelle=350024000AI0073 `
 la fournit 
ainsi que
` https://portail-test.sig.rennesmetropole.fr/cadastrapp/services/getFIC?_dc=1492770344512&parcelle=350024000AI0073&onglet=0`

Il faut faire pour la surface calculée comme pour la contenance dgfip . puisque cette dernière s'affiche bien alors qu'elle n'est pas présente dans la requête avec onglet=1

**Comment by catmorales** [comment]
@fvanderbiest , ne manque t-il pas le champ surface calculée (surfc)  ici ?
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L378-L391

**Comment by catmorales** [comment]
>Il faut faire pour la surface calculée comme pour la contenance dgfip . puisque cette dernière s'affiche bien alors qu'elle n'est pas présente dans la requête avec onglet=1

Désolé , le getparcelle ne permet pas actuellement de récupérer cette info. Donc ren effet, il faut la rapatrier avec getFIC?onglet=0 surfc = surface SIG. A noter que si on ne spécifie pas l'onglet ça passe aussi.

**Comment by catmorales** [comment]
>Je vous laisse corriger sur ce dépot .

fait avec 111a1cf3470d8ec71656519af61218385f6e8062

**Comment by catmorales** [comment]
@fvanderbiest , il reste à récupérer la valeur de surfc avec un getFic (avec ou sans onglet=0)

**Comment by catmorales** [comment]
OK corrigé je viens de vérifier:
![image](https://cloud.githubusercontent.com/assets/4659829/25999615/18808406-3726-11e7-9e39-8bfa77295715.png)
