### ISSUE TITLE
[Addon urbanisme] option manquante dans le  manifest.json

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#47]
L'option "wmsc2wms" n'est pas présente dans ce dépot. Nous l'avions positionné de mémoire afin de pouvoir utiliser des services wms-c dans les impressions

**Comment by fvanderbiest** [comment]
Plus besoin, on récupère les options générales de mapfishapp, cela évite de la duplication inutile de config.

Voir https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L753
