### ISSUE TITLE
[Print NRU ] Pas d'impression de la note de renseignement d'urbanisme

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#48]
Lors d'une demande d'impression de la Note de Renseignement d'Urbanisme, le fichier pdf n'est pas créé et la console boucle sur:
`{"done":true,"status":"error","elapsedTime":219,"waitingTime":0,"error":"org.mapfish.print.wrapper.ObjectMissingException: attribute [spec.attributes.nomProprio] missing","downloadURL":"/urbanisme/report/53392185-b2ca-4d56-8822-3534ff66dc22@971b3eed-3ca0-4477-9815-c7a066fa3511"}`

**Comment by catmorales** [comment]
Serait-ce lié au fait que l'on soit passé d'un simple proprio à une liste de proprio ?
https://github.com/sigrennesmetropole/addon_urbanisme/pull/41

**Comment by catmorales** [comment]
@fvanderbiest peux tu m'expliquer où cela se paramètre ?

**Comment by catmorales** [comment]
Le problème engendre des requêtes en continu à priori , elles ne s'arrêtent pas !

**Comment by catmorales** [comment]
le json obtenu par `https://portail-test.sig.rennesmetropole.fr/cadastrapp/services/getFIC?_dc=1493718599445&parcelle=350024000AS0531&onglet=1 `   est:
`[{"dnulp":"01","comptecommunal":"350024*00051","app_nom_usage":"LES COPROPRIETAIRES","dlign3":"      ` 
Donc si je remplace, https://github.com/camptocamp/georchestra-rennes-configuration/blob/test/urbanisme/templates/print/config.yaml#L24 par app_nom_usage ça doit marcher ?

**Comment by fvanderbiest** [comment]
Il faut essayer, oui je pense que ça marchera.

**Comment by catmorales** [comment]
Non ça ne marche pas et pourtant:

https://github.com/camptocamp/georchestra-rennes-configuration/commit/048361a5906f328d424e52fcbd21d06f5bda5846
et 
https://github.com/camptocamp/georchestra-rennes-configuration/commit/a8016a448b8ad30729cf168fd9d9cf014150049c

Cela ne suffit pas. @fvanderbiest merci de regarder ce point qui empêche le déploiement du module : j'ai désactivé l'addon en prod .

**Comment by catmorales** [comment]
Le ticket #38 est bloqué également sur ce point, en attente correction de camptocamp.

**Comment by fvanderbiest** [comment]
Actuellement le client JS (addon) POSTe sur https://portail-test.sig.rennesmetropole.fr/urbanisme/print/report.pdf:
```json
{
    "layout": "A4 portrait",
    "attributes": {
        "map": {
            "scale": 533.1823959624462,
            "center": [-188917.02890526, 6125844.5252872],
            "dpi": 72,
            "layers": [{
                "type": "geojson",
                "style": {
                    "1": {
                        "fillColor": "#ee9900",
                        "fillOpacity": 0,
                        "hoverFillColor": "white",
                        "hoverFillOpacity": 0.8,
                        "strokeColor": "#ee9900",
                        "strokeOpacity": 1,
                        "strokeWidth": 3,
                        "strokeLinecap": "round",
                        "strokeDashstyle": "solid",
                        "hoverStrokeColor": "red",
                        "hoverStrokeOpacity": 1,
                        "hoverStrokeWidth": 0.2,
                        "pointRadius": 6,
                        "hoverPointRadius": 1,
                        "hoverPointUnit": "%",
                        "pointerEvents": "visiblePainted",
                        "cursor": "pointer",
                        "fontColor": "#000000",
                        "labelAlign": "cm",
                        "labelOutlineColor": "white",
                        "labelOutlineWidth": 3
                    },
                    "version": "1",
                    "styleProperty": "_gx_style"
                },
                "geoJson": {
                    "type": "FeatureCollection",
                    "features": [{
                        "type": "Feature",
                        "properties": {
                            "_gx_style": 1,
                            "objectid": "109562",
                            "codlot": "201703100851460606",
                            "id_parc": "350238000AM0425",
                            "numero": "425",
                            "codcomm": "350238",
                            "codsec": "350238000AM",
                            "codsubsec": "350238000AM01",
                            "figplan": "01",
                            "codarpent": null,
                            "supf": "421.00000000",
                            "urbain": "N",
                            "batie": "N",
                            "ssurf": "420.14040004",
                            "ssurfb": "177.37860739",
                            "scos": "42.21888859",
                            "nonrej": "O"
                        },
                        "geometry": {
                            "type": "Polygon",
                            "coordinates": [
                                [
                                    [-188942.64053454998, 6125826.16784192],
                                    [-188947.59582117083, 6125810.359792637],
                                    [-188963.91949017879, 6125817.443939982],
                                    [-188938.5284327305, 6125877.020748245],
                                    [-188928.16345942908, 6125872.351393226],
                                    [-188942.64053454998, 6125826.16784192]
                                ]
                            ]
                        },
                        "id": "app_urbanisme_parcelle.350238000AM0425.109562"
                    }]
                }
            }, {
                "baseURL": "https://portail-test.sig.rennesmetropole.fr/geoserver/wms",
                "opacity": 1,
                "type": "tiledwms",
                "layers": ["ref_cad:cadastre"],
                "imageFormat": "image/png",
                "styles": [""],
                "customParams": {
                    "TRANSPARENT": "true",
                    "EXCEPTIONS": "application/vnd.ogc.se_xml",
                    "SLD_VERSION": "1.0.0"
                },
                "tileSize": [256, 256]
            }],
            "projection": "EPSG:3857"
        },
        "parcelle": "350238000AM0425",
        "commune": "Rennes",
        "codeSection": "AM",
        "numero": "425",
        "adresseCadastrale": "190 RUE  DE BREST",
        "contenanceDGFiP": 421,
        "surfaceSIG": "",
        "codeProprio": "350238*08414",
        "adresseProprio": "9 RUE FRANCOIS TANGUY PRIGENT  35000 RENNES",
        "libelles": ""
    }
}
```

Effectivement il n'y a pas de champ `nomProprio`, je regarde ça.

**Comment by fvanderbiest** [comment]
Fait et reporté dans votre config, branche `test`.

**Comment by catmorales** [comment]
Merci ! Vu et testé en test, je vais le reporter en prod la semaine prochaine.

**Comment by catmorales** [comment]
Dans notre configuration de test qui a été redéployée, la configuration du printfish est très ancienne et ne prend pas en compte les modifications réalisées ici 292fe255016b50b97bcfb676f9a7693aa8d39635

**Comment by catmorales** [comment]
>Fait et reporté dans votre config, branche test, serveur de test mis à jour.

Avez vous modifié urbanisme.war sur notre plateforme de test car le redéploiement en prod ne fonctionne pas cf https://github.com/camptocamp/georchestra-rennes-configuration/issues/571

**Comment by catmorales** [comment]
>La configuration du printfish ne prend plus en compte les modifications réalisées dans le fichier A4_Portrait.jrxml.
![image](https://cloud.githubusercontent.com/assets/4659829/26100010/df154dfa-3a2c-11e7-8d99-573113b92952.png)

**Comment by catmorales** [comment]
Ok le problème était lié à:
* attribut surfsig manquant cf efe35565192d12a2beefdd52befe284c755e846f
* paramétrage à faire dans le config.yaml: credentials et user-agent
* pas de pb sur le renommage des libellés dans le fichier .jrxml
