### ISSUE TITLE
Manque attribut dans le main.js

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#49]
il manque l'attribut lié à la surface sig
- dans ce dépot:
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L389-L390
- dans la config rennes metropole (qui marche)
https://github.com/camptocamp/georchestra-rennes-configuration/blob/prod/mapfishapp/addons/urbanisme/js/main.js#L391

**Comment by fvanderbiest** [comment]
Je ne comprends donc pas ce commit : https://github.com/camptocamp/georchestra-rennes-configuration/commit/f968500997efbf1140385f5833130fcc9b5625f3

**Comment by fvanderbiest** [comment]
> il manque l'attribut lié à la surface sig

Du coup vous voulez que je l'ajoute dans https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L389-L390 ?

**Comment by catmorales** [comment]
en effet, j'ai voulu redéployer la plateforme de test depuis le dépot officiel

**Comment by catmorales** [comment]
>Du coup vous voulez que je l'ajoute dans https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L389-L390 ?
oui

**Comment by catmorales** [comment]
Mais je ne comprend pas pourquoi il y a une différence entre la configuration que tu m'as mis hier sur la PF de test (que j'ai écrasé depuis) et ce dépot-ci.

**Comment by fvanderbiest** [comment]
Voilà : https://github.com/sigrennesmetropole/addon_urbanisme/commit/efe35565192d12a2beefdd52befe284c755e846f

**Comment by fvanderbiest** [comment]
> une différence

Quelle différence ? Qu'est ce qui ne marche pas ?

**Comment by catmorales** [comment]
>Quelle différence ?

cet attribut

**Comment by catmorales** [comment]
Tu as mis à jour notre configuration depuis un dépot local peut être.

**Comment by catmorales** [comment]
Je vais corriger notre plateforme de test

**Comment by catmorales** [comment]
Fait ! mais il me reste un problème à l'impression.

**Comment by catmorales** [comment]
Il faut rajouter dans le config.yaml:
* credentials
* user agent

**Comment by catmorales** [comment]
OK c'est bon maintenant.
Reste la surface calculée qui est vide . je remets un ticket spécifiquement sur ce point.
