### ISSUE TITLE
Déploiement addon urbanisme

### ISSUE THREAD

**Issue by pmauduit** [sigrennesmetropole/addon_urbanisme#5]
J'ai commencé à reprendre le travail de @jdenisgiguere et j'ai effectué un déploiement sur portail-test (intra).

Quelques remarques:

* Le module urbanisme était au départ prévu pour être un addon mapfishapp (coté client et serveur). Mais ce dernier nécessitant un mapfishprint en v3, je l'ai transformé en webapp à part (reprenant un mfprintv3 + le webservice nécessaire à la récupération des infos dans postgis-bdu. Comme il y avait peu de risques d'interférences avec cadastrapp, j'ai pris la décision de le mettre dans le meme tomcat. Je peux changer toutefois si vous y voyez une objection.

* J'ai configuré la webapp en mode datadir (cf `/srv/tomcat/cadastre/work/urbanisme`). Note: il serait possible d'y stocker aussi le template d'impression mfprint, mais pour l'instant j'utilise celui de Jean-Denis fourni par la webapp.

* J'utilise le compte `postgres` pour me connecter à la base, mais je n'aime pas trop cela car c'est un compte administrateur, c'était le seul que j'avais sous la main. Y-a-t'il un compte plus adapté pour cela ?

* Il y a pour l'instant 2 icones au chargement de l'addon dans mfapp: une qui permet de tester sur une parcelle hardcodée (l'icone la plus à droite):

![urbanisme](https://cloud.githubusercontent.com/assets/594335/16948741/b52b4bb0-4db6-11e6-8035-bdbd627f1764.png)

* D'après ma lecture rapide des specifications de ce module, il semble qu'il ne réagisse qu'en présence de couches spécifiques dans mfapp: lesquelles ? Pour l'instant l'icone de gauche m'indique le message suivant: "Pas de PLU numérique disponible pour cette commune."

* Je devrais pouvoir faire une PR sur ce dépot sous peu.

**Comment by catmorales** [comment]
Est ce normal que je ne vois pas le code du module  dans github ?

**Comment by pmauduit** [comment]
> Est ce normal que je ne vois pas le code du module dans github ?

Je suis passé par une PR il y a quelques minutes: https://github.com/sigrennesmetropole/addon_urbanisme/pull/6

**Comment by catmorales** [comment]
>J'utilise le compte postgres pour me connecter à la base, mais je n'aime pas trop cela car c'est un compte administrateur, c'était le seul que j'avais sous la main. Y-a-t'il un compte plus adapté pour cela ?
cela dépend de l'instance de base où vous avez stocké les données . je pense que www-data devrait fonctionner.

**Comment by catmorales** [comment]
mais je ne vois que le README et le fichier de LICENCE. N'y a-t'il pas un pb de droit ?

**Comment by pmauduit** [comment]
> mais je ne vois que le README et le fichier de LICENCE. N'y a-t'il pas un pb de droit ?

il y a tout le code dans ma PR, qui provient de mon fork du dépot (https://github.com/pmauduit/addon_urbanisme), je n'ai pas les droits d'écriture sur l'organisation sigrennesmetropole sur github.

**Comment by catmorales** [comment]
> je n'ai pas les droits d'écriture sur l'organisation sigrennesmetropole sur github.

Je viens de t'envoyer une invitation pour t'ajouter dans la liste des "members".

**Comment by pmauduit** [comment]
ok, accepté, mais comme dit dans les commentaires sur la PR, je vais attendre les retours de Francois pour la partie JS car je ne suis pas compétent la dessus

**Comment by catmorales** [comment]
>Pour l'instant l'icone de gauche m'indique le message suivant: "Pas de PLU numérique disponible pour cette commune."

Ce message apparaît si il n'existe pas encore de PLU numérique pour la commune sur laquelle tu es positionné. C'est ce que nous avions vu avec Jean-denis cf https://github.com/sigrennesmetropole/addon_urbanisme/issues/2.
En effet , toutes les communes n'ont pas de plu numérisé, c'est un travil de longue haleine qui est en cours de constitution .

**Comment by catmorales** [comment]
Par contre là il apparaît par défaut ... et pas au clic sur la carte.
Il y a du paramétrage à faire.
La parcelle hardcodée ne contient pas la carte...

**Comment by catmorales** [comment]
Pour les données à utiliser cf le document de spécifications, je vais regarder le datadir.

**Comment by catmorales** [comment]
Concernant la connexion à la base bdu de postgis-bdu (intranet) ou la base bdu en extranet, nous utilisons un compte spécifique je vais le paramétrer dans le datadir et relancer le tomcat-cadastre

**Comment by catmorales** [comment]
@pmauduit les fichier work/urbanisme.properties et work/logback.xml appartiennent à root, je ne peux pas les modifier ...

**Comment by pmauduit** [comment]
Je vais le faire, désolé

**Comment by pmauduit** [comment]
c'est fait

**Comment by catmorales** [comment]
Moi aussi. mais même problème. il faut paramétrer la couche wms zonage plu sans doute dans l'addon ?

**Comment by pmauduit** [comment]
> il faut paramétrer la couche wms zonage plu sans doute dans l'addon ?

Oui je pense, le fichier de config est ici: `/srv/tomcat/georchestra/webapps/mapfishapp/app/addons/urbanisme/config.json`

**Comment by catmorales** [comment]
pour info le service est: **urba_fonc:plu_zone_urba**.
Je vais regarder l'addon.

**Comment by catmorales** [comment]
j'ai juste changé l'url qui tapait sur la prod et le libellé Information PLU:
```
[
    {
        "id": "urbanisme_0",
        "enabled": true,
        "name": "Urbanisme",
        "options": {
            "parcellesCadastralesLayer": "ref_cad:app_cadastrapp_parcelle",
            "zonesPluLayer": "urba_fonc:plu_zone_urba",
            "cadastrappUrl": "/cadastrapp/services/",
            "printServerUrl": "/urbanisme/",
            "fileServerUrl": "https://portail-test.sig.rennesmetropole.fr/fichiers/index.php",
            "fileRepositoryId": "a00a272df0c4760a610ee97ca6f648fc"
        },
        "title": {
            "en": "Land Planning",
            "es": "Urbanisme",
            "fr": "Urbanisme",
            "de": "Urbanisme"
        },
        "description": {
            "en": "Urban planning information",
            "fr": "Information PLU",
            "es": "...",
            "de": "..."
        }
    }
]

```

**Comment by catmorales** [comment]
toujours un problème de permission .... car c'est au nom de pmauduit

**Comment by pmauduit** [comment]
grmbl, je modifie, cela m'étonne car ce n'est pas le genre de choses que j'oublie d'habitude

**Comment by catmorales** [comment]
besoin de vacances ;)

**Comment by pmauduit** [comment]
c'est fait ;)

**Comment by catmorales** [comment]
J'ai fait la modification puis relancé le service tomcat-georchesta. toujours pareil. 
Pour info: l'icône concernant le zonage PLU ne s'enlève pas lors de la désactivation de l'addon dans l'interface (retrait de l'outil) ce bouton ne semble pas opérationnel.
La connexion à la base est bonne puisque le deuxième bouton fonctionne: il charge bien la donnée de la parcelle hardocodée en dynamique ?

**Comment by pmauduit** [comment]
> La connexion à la base est bonne puisque le deuxième bouton fonctionne: il charge bien la donnée de la parcelle hardocodée en dynamique ?

Quand j'avais fait l'essai, oui, je voyais des requetes HTTP vers le webservice urbanisme + cadastrapp

**Comment by catmorales** [comment]
Concernant le bouton zonage plu il n'y a pas de logs dans urbanisme .log contrairement à l'autre bouton.

**Comment by catmorales** [comment]
Pour le moment ce n'est pas opérationnel.

**Comment by pmauduit** [comment]
j'ai demandé des explications @jdenisgiguere sur le fonctionnement

**Comment by pmauduit** [comment]
> Concernant le bouton zonage plu il n'y a pas de logs dans urbanisme .log contrairement à l'autre bouton.

c'est normal, urbanisme.log ne va se remplir qu'en cas de requête sur ses webservices, dans le cas du zonage PLU cela ne semble pas etre le cas, (j'ai juste une requete WMS GetFeatureInfo vers le geoserver, et une requête vers cadastrapp). Dans le 2eme cas, on a bien un appel sur urbanisme/renseignUrba.

**Comment by pmauduit** [comment]
Suite discussion avec Jean-Denis, j'arrive à utiliser l'outil, il est par contre nécessaire de charger les 2 couches à la main, ce que je n'avais pas compris.

Parcelle cadastrale:

![parc-cad](https://cloud.githubusercontent.com/assets/594335/17021913/52448890-4f4b-11e6-8c19-edb6494d17e9.png)

Zonage PLU:

![zonage-plu](https://cloud.githubusercontent.com/assets/594335/17021919/5f9d99c8-4f4b-11e6-93d9-39e352260859.png)

**Comment by catmorales** [comment]
En effet , ce n'était pas ainsi dans les specs de mémoire , il faut que les couches soient chargées au moment du chargement de l'addon si elles ne sont pas présentes dans la carte.

**Comment by catmorales** [comment]
OK merci de l'info.
j'ai vu et reproduit et je vais pouvoir maintenant le tester.
Il faut que les couches soient **préalablement** chargées au moment de l'activation de l'addon sinon cela ne fonctionne pas (si on les charge après l'addon). 
Ce fonctionnement n'est pas suffisant et non conforme aux specs.
je suggère de mettre un ticket sur ce site par anomalie rencontrée.

**Comment by jdenisgiguere** [comment]
C'est une excellente idée d'ouvrir un ticket par anomalie. Merci @catmorales ! Je ferai le suivi avec @fvanderbiest pour la question de la conformité aux spécifications.

**Comment by jdenisgiguere** [comment]
Je propose que l'on ferme cette anomalie. Nous pourrons effectuer le suivi des anomalies par ticket. N'hésitez pas à rouvrir et commenter s'il y a des aspects qu'il serait plus cohérent de traiter ici.
