### ISSUE TITLE
[NRU] Web et Print - champ surface calculée vide

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#50]
sans doute lié à #40 et #42 
La surface calculée des parcelles ne s'affiche pas ni dans l'interface web ,ni dan sle print.
* Web:
![image](https://cloud.githubusercontent.com/assets/4659829/26206440/22027d0e-3be5-11e7-992b-8c1fd7bbfe8e.png)

* Impression:
![image](https://cloud.githubusercontent.com/assets/4659829/26206486/4415f5b0-3be5-11e7-9904-561b42adef95.png)

**Comment by fvanderbiest** [comment]
Le champ `surfc`, initialement présent dans la réponse du service `/cadastrapp/services/getParcelle` a disparu. 

cf https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L383-L411

Ceci explique cela...

**Comment by fvanderbiest** [comment]
Est-ce qu'il ne faut pas plutot aller chercher l'information dans le retour du GetFeatureInfo ?

J'y vois
```xml
            <ref_cad:ssurf>273.32729999</ref_cad:ssurf>
            <ref_cad:ssurfb>208.02774687</ref_cad:ssurfb>
```

**Comment by fvanderbiest** [comment]
Pour moi ce n'est pas un bug mais une évolution, car cela ne correspond plus aux specs initiales ...
![capture du 2017-08-30 11-13-09](https://user-images.githubusercontent.com/265319/29864871-4342e946-8d74-11e7-881c-36423631be7b.png)

**Comment by catmorales** [comment]
Ceci a été fait sur la v2.1
