### ISSUE TITLE
[NRU] Impression - la carte n'est pas centrée sur la parcelle 

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#51]
![image](https://cloud.githubusercontent.com/assets/4659829/26207876/019e3edc-3be9-11e7-887e-790a51a5aea9.png)

Cette évolution est à faire en concordance avec https://github.com/georchestra/cadastrapp/issues/335.
Le même comportement dans les deux cas est souhaité.

**Comment by fvanderbiest** [comment]
Fait avec 92489fd
