### ISSUE TITLE
[PLU] Confusion date d'approbation / date de validité des données

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#52]
![screenshot677](https://cloud.githubusercontent.com/assets/6370443/26355911/a27fad4c-3fca-11e7-9148-1de4f36128f9.png)

Comme on le voit sur cette capture d'écran, la date qui devrait apparaître pour ce PLU en vigueur est "20/10/2016" et non pas "12/04/2016".

**Il y a une confusion entre la date d'approbation du PLU et la date de validation des données !**

Définition CNIG de l'attribut ```datvalid / dateValidation```  : _Date de la dernière validation de la zone ou de son règlement. Cette date correspond à celle du dernier changement apporté à la zone ou à son règlement. La dateValidation est donc antérieure ou égale à la date d'approbation du document d'urbanisme auquel appartient la zone._ (p. 34 du standard CNIG PLU octobre 2014).

La difficulté est que la date d'approbation du PLU n'apparaît pas comme attribut à part entière dans cette couche. Cette information est en effet stockée dans l'attribut ```datappro``` de la table plu_document_urba. Et il n'est pas souhaitable pour diverses raison de créer une vue geoserver pour aller récupérer cet attribut.

La correction est sans doute à faire entre les lignes 216 et 231 : https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/src/addon/urbanisme/js/main.js#L216-L231

**Je recommande donc d'utiliser la date d'approbation du PLU qui est explicitement dans ```id_docurba``` pour en découler un nouvel attribut ```datappro``` qui est à utiliser pour l'affichage et la construction de l'url du fichier ZIP.**

**Comment by catmorales** [comment]
corrigé et déployé en test . OK
A mettre en prod

**Comment by alebras** [comment]
Mis en prod intra et extranet
