### ISSUE TITLE
Demande évolutions pour le PLUi (décembre 2019 / février 2020)

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#60]
Dans le cadre de la mise en production des données du PLUi, je suggère ici quelques évolutions.
Ces demandes sont faites en concertation avec F TRESSE du SPEU.

**1. Renommer le bouton "PLU" en "Zonage"**

**2. Changer l'ordre des boutons**
De gauche à droite :  Zonage |  NRU  |  ADS

**3. couche PLUi à charger**
L'outil devrait charger la future couche "plui_plan_zonage".
2 avantages : 
- on se passe d'une couche applicative qui arrive comme un cheveu sur la soupe actuellement
- cette couche est conforme au règlement graphique alors que la couche actuelle "plu_zone_urba" est stylée avec les destinations dominantes et disparaîtra de toute façon le 04/02/2020

**Comment by MaelREBOUX** [comment]
Modifications de la demande initiale.

**Comment by catmorales** [comment]
A voir avec la MOA du projet urbanisme @ThomasBruleOpen

**Comment by MaelREBOUX** [comment]
oui et d'autres besoins sont remontés depuis les formations de la semaine dernière.

**Comment by ThomasBruleOpen** [comment]
En cours
PR Désactivation du bouton PLU #65

**Comment by catmorales** [comment]
fait sur la v2.1
