### ISSUE TITLE
[Général] Chargement des couches  nécessaires à l'addon

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#7]
Actuellement les couches paramétrées dans le config.json (urba_fonc:plu_zone_urba et ref_cad:app_cadastrapp_parcelle) doivent être préalablement chargées au moment de l'activation de l'addon sinon cela ne fonctionne pas (si on les charge après l'addon). 
Les utilisateurs ne peuvent pas gérer cette contrainte.

Dans la logique, il nous faudrait un comportement similaire à celui du  module cadastre à savoir:

* l'activation de l'addon charge les couches si elles ne sont pas présentes,
* un message d'information s'affiche au moment du chargement de l'addon pour indiquer aux utilisateurs que les couchesurba_fonc:plu_zone_urba et ref_cad:app_cadastrapp_parcelle sont nécessaires au bon fonctionnement du module (ça évitera qu'ils les déchargent intempestivement) (message comme lors du chargement d'un contexte),
* si elles sont présentes, il les complète avec le i d'interrogation,
* la désactivation de l'addon retire la fonctionnalité i des couches, (on évitera de les retirer car si elles étaient présentes au préalable c'est que l'utilisateur en avait besoin pour autre chose par ex module cadastre).

**Comment by catmorales** [comment]
>l'activation de l'addon charge les couches 

ou un contexte spécifique qui s'ajoute à la carte courante

**Comment by catmorales** [comment]
>si elles sont présentes, il les complète avec le i d'interrogation,

* ça n'a pas fonctionné lors de mon test

>la désactivation de l'addon retire la fonctionnalité i des couches, 

* ça n'a pas fonctionné lors de mon test --> on peut cliquer sur un "i" orange alors que l'addon est désactivé (dans les outils)

**Comment by jdenisgiguere** [comment]
Voici ce que les spécifications indiquent par rapport au chargement des couches.

> Dès que l’addon sera chargé :
toutes les couches déjà chargées seront examinées. Si l’une correspond à celles fournies dans la configuration, l’addon modifiera sa barre d’outil en propre de manière à y ajouter une icone (“i” orange par exemple) correspondant à un outil d’interrogation métier 
si une de ces couches est chargée a posteriori, ce nouveau (i) sera déjà présent.
Si cela n’est techniquement pas possible : l’outil sera présent dans le menu actions (car généré post chargement de l’addon et des couches).

Étant donné qu'on indique que le (i) devra apparaître si on charge la couche a posteriori, il me semble raisonnable de penser qu'il est question d'un chargement par l'utilisateur et non pas par l'addon.

**Comment by jdenisgiguere** [comment]
J'ai créé une anomalie distincte pour la désactivation de l'addon https://github.com/sigrennesmetropole/addon_urbanisme/issues/9 .

**Comment by catmorales** [comment]
C'est vrai, ça peut être vu comme ça. 
Ca manque de précision  mais il faut trouver une solution pratique pour l'utilisateur et simple à implémenter.
Pour revenir sur la commande initiale (cf cahier des charges initial), la solution qui avait été pensée initialement était le chargement d'un contexte spécifique lié à l'addon contenant les couches nécessaires avec  la symbologie adéquate. 
Si on reste sur cette idée , je vois plusieurs  possibilités:

1 . intégrer ces couches dans le contexte par défaut qui sera non plus cadastre mais cadastre-urbanisme
 * pas terrible pour les utilisateurs qui ne feront pas d'urbanisme mais à discuter avec la maîtrise d'ouvrage @MaelREBOUX ,

2 . charger ce contexte automatiquement lors de l'activation de l'addon (l'ajouter à la carte courante),
*  @jdenisgiguere implémentation complexe de votre côté ? gestion des couches si présentes compatibles ?

Dans tous les cas, il me semble indispensable d'informer l'utilisateur du fonctionnement dans un message affiché lors de l'activation de l'addon surtout si il n'y a plus de boutons dans l'interface cf https://github.com/sigrennesmetropole/addon_urbanisme/issues/8
** @jdenisgiguere implémentation complexe de votre côté ?

Je propose de créer ce contexte "administrateur" sur notre PF de test et de refaire les tests avec, pour voir  de notre côté comment serait l'expérience utilisateur...

**Comment by catmorales** [comment]
Par contre ce bug reste présent:

>si elles sont présentes, il les complète avec le i d'interrogation,

ça n'a pas fonctionné lors de mon test

**Comment by jdenisgiguere** [comment]
L'ajout d'une couche n'est pas d'une très grande complexité. Il faut tout de même bien le faire pour éviter des problèmes de conflit. Il faudrait aussi modifier la configuration de l'addon pour avoir toute l'information requise. 

La diffusion d'un avertissement au sujet des couches requises est assez directe.

Pour ce qui est du chargement d'un contexte, j'imagine que ça peut causer des ennuis dans certains cas d'utilisation. Est-ce possible?


@fvanderbiest, ton expertise sur les différentes stratégies d'implantation sera plus que la bienvenue!

**Comment by catmorales** [comment]
Je rajoute l'élément suivant sur la table pour alimenter la réflexion
Le module cadastrapp et le module urbanisme utilisent tous deux la même couche de parcelle.
Celle-ci est déjà préchargée par le module cadastrapp (elle peut être rendue visible ou non) , il est donc inutile de la charger deux fois (ou que l'utilisateur la voit deux fois) .
Il faut donc que nous ayons une réflexion globale sur l'utilisation de ces deux modules qui vont la plupart du temps aller de pair.
Je suggère donc d'attendre le retour de @MaelREBOUX afin que j'échange avec lui sur le fonctionnement idéal avant de faire des évolutions de ce module sur ce point.

**Comment by catmorales** [comment]
A des fins de test, je viens de créer sur testgeorchestra un contexte "Urbanisme" qui contient les 2 couches utiles et une autre donnée utile pour l'urbanisme.
![image](https://cloud.githubusercontent.com/assets/4659829/17290690/0a9706b0-57e0-11e6-804b-22a7db2c22d8.png)

**Comment by MaelREBOUX** [comment]
lié à #8 et #9

**Comment by catmorales** [comment]
j eferme car doublon de #8
