### ISSUE TITLE
Chargement / déchargement de la couche urbanisme_parcelle à revoir

### ISSUE THREAD

**Issue by MaelREBOUX** [sigrennesmetropole/addon_urbanisme#74]
Je croyais avoir fait ce ticket il y a longtemps pourtant.

Il faudrait que le comportement de cet addon soit aligné sur le comportement de cadastrapp. A savoir :
1. chargement silencieux de la couche = la couche n'apparaît pas dans la TOC, elle est masquée.
2. décharger la couche (même masquée) de la TOC quand on ferme l'addon. actuellement la couche reste.
3. la méthode de chargement de la couche oblige à ce que la couche applicative soit publicisée (= présente dans les capacités WxS) alors que pas nécessaire avec Cadastrapp

**Comment by catmorales** [comment]
ce ticket a été pris en compte lors des dernières corrections https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/issues/42
