### ISSUE TITLE
[Général] Ergonomie générale - interface à finaliser

### ISSUE THREAD

**Issue by catmorales** [sigrennesmetropole/addon_urbanisme#8]
Actuellement , ces boutons ne correspondent pas au comportement des "i " présents dans les couches individuelles.
Voir ce qu'il est prévu de mettre  derrière.  A échanger avec @MaelREBOUX .

**Comment by jdenisgiguere** [comment]
Est-ce que ces boutons ont une forte valeur pour vous? 

Nous pourrions limiter les risques de confusion en laissant uniquement les boutons dans les barres d'outils des couches parcelles cadastrales et zonage de PLU.

**Comment by catmorales** [comment]
Oui c'est ce que nous sommes en train de penser également de notre côté mais il nous faut valider cela avec @MaelREBOUX qui ne revient que début août.

**Comment by MaelREBOUX** [comment]
Bonjour,

Suite à des discussions internes et avec des utilisateurs, il ressort les points suivants

**"i" spécifique**
On garde le principe de l'ajout du "i" spécifique à côté du "i" générique sur la ou les couches ciblées par l'add-on.
Ce principe a été pensé il y a longtemps et on confirme qu'on veut le mettre en oeuvre. Bien d'autres couches seront concernées dans notre SIG par ce besoin / fonctionnalité permettant d'ouvrir une fiche d'infos spécifique.
L'add-on, lorsqu'il est chargé, doit donc bien vérifier, à chaque changement dans la TOC (essentiellement présence / chargement) la présence des couches cibles. Tous les cas sont à voir dans le détail dans une issue spécifique.

Note : côté "ergonomie" : je voudrais la même image que le i bleu mais avec un fond rouge "i rouge".

**barre d'outils**
Afin d'homogénéiser les outils existants (cadastre) et à venir : créer une barre d'outils spécifique pour cette add-on.
La barre d'outil comportera 3 boutons :
- i interroger un zonage PLU
- i interroger une parcelle cadastrale pour obtenir une note de renseignement d'urbanisme
- bouton aide qui renverra à la documentation en ligne (cf bouton similaire sur cadastrapp + discussions en cours sur la liste). L'ul doit se trouver dans le config. json pour être facilement paramétrable.

Si l'utilisateur clique sur un des boutons i et si la couche cible n'est pas dans la TOC -> la charger. Cela permet d'offrir à l'utilisateur une roue de secours s'il supprime la couche des zonages. La barre d'outils étant chargée, le clic sur le i ce cette dernière provoque le chargement de la couche.

**Comment by catmorales** [comment]
En attendant de disposer de la barre d'outils qui me semble effectivement nécessaire pour avoir une homogénéité des comportements des outils (et ne pas perdre les utilisateurs), merci de cacher les 2 boutons inutiles dans l'interface qui n'étaient présents que pour les tests de jean-denis.
![image](https://cloud.githubusercontent.com/assets/4659829/19144481/27277064-8baa-11e6-96e9-7961b6b9f1bc.png)

**Comment by catmorales** [comment]
@fvanderbiest ce point est également gênant pour la mise en production du module. 
L'ajout de la barre d'outil et la suppression des 2 boutons de test sont indispensable car les utilisateurs vont se perdre... 
On voit bien après quelques semaines d'usage qu'ils ont besoin d'avoir des repères et des fonctionnements homogènes à savoir: 1 outil = 1 barre d'outil à l'instar des outils de dessin, de mesure avancée, cadastrapp, ....

**Comment by MaelREBOUX** [comment]
je confirme.
il faut également modifier l'image pour avoir le "i rouge".

**Comment by catmorales** [comment]
relance :  
* cacher les 2 boutons inutiles dans l'interface qui n'étaient présents que pour les tests de jean-denis.
image 
* barre d'outils 
* i rouge

**Comment by catmorales** [comment]
Ce ticket est important à traiter pour la livraison finale

**Comment by fvanderbiest** [comment]
Suppression des 2 boutons inutiles avec c99c58e

**Comment by fvanderbiest** [comment]
Bouton rouge avec 7654963

**Comment by fvanderbiest** [comment]
Pour moi, la barre d'outil est en évolution, elle n'est pas dans les specs.

**Comment by catmorales** [comment]
@fjacon relance car on a des réunions de présentation de ce module prévues en mars et il faut que ce soit disponible - A prendre en assistance
Merci d'avance
