### ISSUE TITLE
[Général] Déchargement de l'addon

### ISSUE THREAD

**Issue by jdenisgiguere** [sigrennesmetropole/addon_urbanisme#9]
Le déchargement de l'addon ne désactive pas les fonctionnalités.

Au déchargement, les boutons d'interrogation devrait être retirés des barres d'outils.

**Comment by jdenisgiguere** [comment]
À tester après l'intégration dans l'environnement de développement de la PR #14 .

**Comment by MaelREBOUX** [comment]
lier à #7 et #8

**Comment by catmorales** [comment]
Je viens de le tester et ça marche.
